// Industry-to-section recipe mapping
// Maps each of the 25 industries to the best section variants for their site

export interface SectionRecipe {
  hero: string;
  services: string;
  about: string;
  testimonials: string;
  cta: string;
  faq: string;
  footer: string;
  navbar: string;
}

// Maps industry slug → recommended section recipe
export const INDUSTRY_RECIPES: Record<string, SectionRecipe> = {
  hvac: {
    hero: 'full-bleed',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  plumbing: {
    hero: 'full-bleed',
    services: 'icon-list',
    about: 'stats-bar',
    testimonials: 'carousel',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  electrical: {
    hero: 'full-bleed',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  dental: {
    hero: 'gradient-overlay',
    services: 'alternating',
    about: 'team-grid',
    testimonials: 'carousel',
    cta: 'form-embed',
    faq: 'two-column',
    footer: 'map-contact',
    navbar: 'sticky-white',
  },
  legal: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'photo-split',
    testimonials: 'single-spotlight',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  restaurant: {
    hero: 'split-screen',   // split-screen: photo-heavy, shows food/ambiance well
    services: 'tabs',
    about: 'timeline',
    testimonials: 'carousel',
    cta: 'floating-bar',
    faq: 'two-column',
    footer: 'map-contact',
    navbar: 'transparent-overlay',
  },
  'real-estate': {
    hero: 'split-screen',
    services: 'grid-3col',
    about: 'photo-split',
    testimonials: 'grid-cards',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  auto: {
    hero: 'full-bleed',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  'med-spa': {
    hero: 'gradient-overlay',
    services: 'alternating',
    about: 'team-grid',
    testimonials: 'single-spotlight',
    cta: 'form-embed',
    faq: 'two-column',
    footer: 'minimal',
    navbar: 'transparent-overlay',
  },
  fitness: {
    hero: 'gradient-overlay',   // gradient-overlay: energetic, bold — perfect for fitness
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'carousel',
    cta: 'floating-bar',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'hamburger',
  },
  veterinary: {
    hero: 'gradient-overlay',
    services: 'icon-list',
    about: 'team-grid',
    testimonials: 'carousel',
    cta: 'form-embed',
    faq: 'two-column',
    footer: 'map-contact',
    navbar: 'sticky-white',
  },
  consulting: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'photo-split',
    testimonials: 'single-spotlight',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'minimal',
    navbar: 'sticky-white',
  },
  roofing: {
    hero: 'full-bleed',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  landscaping: {
    hero: 'split-screen',
    services: 'alternating',
    about: 'photo-split',
    testimonials: 'grid-cards',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  'lawn-care': {
    hero: 'split-screen',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'carousel',
    cta: 'phone-banner',
    faq: 'two-column',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  cleaning: {
    hero: 'gradient-overlay',
    services: 'icon-list',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  painting: {
    hero: 'split-screen',
    services: 'alternating',
    about: 'photo-split',
    testimonials: 'carousel',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  flooring: {
    hero: 'split-screen',
    services: 'alternating',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  remodeling: {
    hero: 'full-bleed',
    services: 'alternating',
    about: 'timeline',
    testimonials: 'grid-cards',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  'pest-control': {
    hero: 'full-bleed',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'carousel',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  locksmith: {
    hero: 'full-bleed',
    services: 'icon-list',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'map-contact',
    navbar: 'sticky-white',
  },
  moving: {
    hero: 'split-screen',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'carousel',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  salon: {
    hero: 'gradient-overlay',
    services: 'tabs',
    about: 'team-grid',
    testimonials: 'single-spotlight',
    cta: 'floating-bar',
    faq: 'two-column',
    footer: 'minimal',
    navbar: 'transparent-overlay',
  },
  medical: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'team-grid',
    testimonials: 'single-spotlight',
    cta: 'form-embed',
    faq: 'two-column',
    footer: 'map-contact',
    navbar: 'sticky-white',
  },
  accounting: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'photo-split',
    testimonials: 'single-spotlight',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'minimal',
    navbar: 'sticky-white',
  },

  // ── New Industries (Mar 26) ──────────────────────────────────────────

  cannabis: {
    hero: 'gradient-overlay',
    services: 'grid-3col',
    about: 'photo-split',
    testimonials: 'grid-cards',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  contractor: {
    hero: 'full-bleed',
    services: 'alternating',
    about: 'timeline',
    testimonials: 'grid-cards',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  insurance: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'stats-bar',
    testimonials: 'single-spotlight',
    cta: 'form-embed',
    faq: 'two-column',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  photography: {
    hero: 'split-screen',
    services: 'alternating',
    about: 'photo-split',
    testimonials: 'single-spotlight',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'minimal',
    navbar: 'transparent-overlay',
  },
  chiropractic: {
    hero: 'gradient-overlay',
    services: 'icon-list',
    about: 'team-grid',
    testimonials: 'carousel',
    cta: 'form-embed',
    faq: 'two-column',
    footer: 'map-contact',
    navbar: 'sticky-white',
  },
  therapy: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'photo-split',
    testimonials: 'single-spotlight',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'minimal',
    navbar: 'sticky-white',
  },
  'pet-services': {
    hero: 'split-screen',
    services: 'grid-3col',
    about: 'photo-split',
    testimonials: 'carousel',
    cta: 'phone-banner',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  wedding: {
    hero: 'gradient-overlay',
    services: 'alternating',
    about: 'photo-split',
    testimonials: 'single-spotlight',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'minimal',
    navbar: 'transparent-overlay',
  },
  mortgage: {
    hero: 'centered-badge',
    services: 'icon-list',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'split-offer',
    faq: 'two-column',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
  telecom: {
    hero: 'gradient-overlay',
    services: 'grid-3col',
    about: 'photo-split',
    testimonials: 'grid-cards',
    cta: 'split-offer',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  },
};

/** Get recipe for an industry, falling back to a sensible default */
export function getRecipeForIndustry(industry: string): SectionRecipe {
  return INDUSTRY_RECIPES[industry] || {
    hero: 'gradient-overlay',
    services: 'grid-3col',
    about: 'stats-bar',
    testimonials: 'grid-cards',
    cta: 'form-embed',
    faq: 'accordion',
    footer: 'four-column',
    navbar: 'sticky-white',
  };
}
