// ── Role Worker Definitions ──────────────────────────────────────────────────
// Shared data for all role-based AI workers.
// Used by both the AI Workers tab and the AI Setup page.

export interface TemplateVariable {
  key: string;
  label: string;
  placeholder: string;
  required: boolean;
  type?: 'text' | 'textarea' | 'select';
  options?: string[];
}

export interface RoleWorker {
  id: string;
  type: 'role';
  emoji: string;
  name: string;
  description: string;
  roleBadge: string;
  tags: string[];
  whatItDoes: string[];
  channels: ('sms' | 'voice' | 'chat' | 'telegram')[];
  tools: string[];
  variables?: TemplateVariable[];
  soulMd?: string;  // The actual SOUL.md content pushed to container
}

export const ROLE_WORKERS: RoleWorker[] = [
  {
    id: 'sales-qualifier', type: 'role', emoji: '🎯', name: 'Sales Qualifier',
    roleBadge: 'Lead Qualification',
    description: 'Engages new leads via text and voice, asks qualification questions using the BANT framework, scores fit, and routes qualified leads to book meetings with your team.',
    tags: ['leads', 'qualification', 'BANT', 'booking'],
    whatItDoes: [
      'Engages new leads instantly via SMS or chat',
      'Qualifies using BANT (Budget, Authority, Need, Timeline)',
      'Routes hot leads to book a meeting automatically',
      'Gracefully disqualifies bad fits without burning the relationship',
    ],
    channels: ['sms', 'chat', 'voice'],
    tools: ['Books Appointments', 'Tags Contacts', 'Creates Deals', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'qualification_criteria', label: 'Qualification Criteria', placeholder: 'Budget over $5k, decision maker, timeline within 90 days...', required: false, type: 'textarea' },
      { key: 'ideal_customer', label: 'Ideal Customer Profile', placeholder: 'Small business owners in home services with 5-50 employees', required: false },
      { key: 'disqualification_response', label: 'Disqualification Response', placeholder: 'Thanks for your interest! Based on what you shared, we might not be the best fit right now...', required: false, type: 'textarea' },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team/discovery', required: false },
    ],
  },
  {
    id: 'appointment-setter', type: 'role', emoji: '📞', name: 'Appointment Setter',
    roleBadge: 'Scheduling',
    description: 'Specializes in booking, confirming, and rescheduling appointments with zero friction. Handles scheduling logistics so your team focuses on the meeting, not the calendar.',
    tags: ['scheduling', 'calendar', 'reminders', 'booking'],
    whatItDoes: [
      'Books, confirms, and reschedules appointments 24/7',
      'Handles multiple appointment types and calendar logistics',
      'Sends confirmation messages with all details',
      'Manages reschedule requests without human intervention',
    ],
    channels: ['sms', 'chat', 'voice'],
    tools: ['Books Appointments', 'Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'appointment_types', label: 'Appointment Types', placeholder: 'Free consultation - 30min\nStrategy session - 60min\nQuick check-in - 15min', required: false, type: 'textarea' },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team', required: false },
      { key: 'reschedule_policy', label: 'Reschedule Policy', placeholder: 'Reschedule up to 2 hours before. No-shows get one follow-up.', required: false },
      { key: 'reminder_message', label: 'Reminder Message Template', placeholder: 'Just a friendly reminder about your upcoming appointment...', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'intake-specialist', type: 'role', emoji: '📋', name: 'Intake Specialist',
    roleBadge: 'Client Onboarding',
    description: 'Collects required information from new clients or patients to complete onboarding. Walks through each field patiently and routes to the right department when done.',
    tags: ['intake', 'onboarding', 'forms', 'routing'],
    whatItDoes: [
      'Collects required client/patient info one field at a time',
      'Routes completed intakes to the right department',
      'Sends confirmation when intake is complete',
      'Handles partial info gracefully with follow-up',
    ],
    channels: ['sms', 'chat'],
    tools: ['Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'required_fields', label: 'Required Fields', placeholder: 'Full name\nDate of birth\nInsurance provider\nReason for visit', required: false, type: 'textarea' },
      { key: 'routing_rules', label: 'Routing Rules', placeholder: 'Insurance questions → billing team\nUrgent care → nurse line\nGeneral inquiry → front desk', required: false, type: 'textarea' },
      { key: 'confirmation_message', label: 'Confirmation Message', placeholder: 'All set! We have everything we need. A team member will reach out within 24 hours.', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'community-manager', type: 'role', emoji: '💬', name: 'Community Manager',
    roleBadge: 'Customer Support',
    description: 'Answers FAQs, handles customer support, and maintains your brand tone across every interaction. Knows when to answer confidently and when to escalate to a human.',
    tags: ['support', 'FAQ', 'community', 'escalation'],
    whatItDoes: [
      'Answers FAQs instantly using your knowledge base',
      'Maintains your brand tone across every interaction',
      'Detects when to escalate to a human vs handle solo',
      'Handles support tickets, complaints, and general inquiries',
    ],
    channels: ['sms', 'chat', 'telegram'],
    tools: ['Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'faq_topics', label: 'Common FAQ Topics & Answers', placeholder: 'What are your hours? → Mon-Fri 9am-5pm EST\nDo you offer refunds? → Yes, within 30 days...', required: false, type: 'textarea' },
      { key: 'escalation_triggers', label: 'Escalation Triggers', placeholder: 'Refund requests\nLegal complaints\nBilling disputes\nAngry/abusive language', required: false, type: 'textarea' },
      { key: 'tone_guidelines', label: 'Tone Guidelines', placeholder: 'Professional but approachable. Use first names. Never use jargon.', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'researcher', type: 'role', emoji: '🔍', name: 'Researcher',
    roleBadge: 'Intelligence',
    description: 'Deep dives into topics on demand, compiles structured reports, tracks industry trends, and delivers actionable intelligence your team can act on immediately.',
    tags: ['research', 'reports', 'analysis', 'intelligence'],
    whatItDoes: [
      'Deep dives into any topic on demand',
      'Compiles structured reports with actionable intelligence',
      'Tracks competitors, trends, and industry news',
      'Delivers findings in your preferred format',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'research_topics', label: 'Default Research Topics', placeholder: 'AI adoption in healthcare\nCompetitor pricing changes\nRegulatory updates', required: false, type: 'textarea' },
      { key: 'competitors', label: 'Key Competitors', placeholder: 'Competitor A\nCompetitor B\nCompetitor C', required: false, type: 'textarea' },
      { key: 'report_format', label: 'Report Format', placeholder: 'Executive Summary', required: false, type: 'select', options: ['Executive Summary', 'Detailed Analysis', 'Quick Brief'] },
    ],
  },
  {
    id: 'weekly-reporter', type: 'role', emoji: '📊', name: 'Weekly Reporter',
    roleBadge: 'Analytics',
    description: 'Compiles periodic business activity summaries — conversations, leads, metrics, notable events — into clear, actionable reports your team actually reads.',
    tags: ['reports', 'analytics', 'metrics', 'weekly'],
    whatItDoes: [
      'Compiles conversation and lead metrics weekly',
      'Flags significant changes (up or down) automatically',
      'Delivers clear summaries your team actually reads',
      'Tracks custom KPIs you define',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Reads Analytics', 'Sends Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'report_metrics', label: 'Metrics to Track', placeholder: 'New leads\nCalls made\nAppointments booked\nRevenue closed\nCustomer satisfaction', required: false, type: 'textarea' },
      { key: 'report_schedule', label: 'Report Schedule', placeholder: 'Weekly', required: false, type: 'select', options: ['Weekly', 'Bi-weekly', 'Monthly'] },
      { key: 'highlight_threshold', label: 'Highlight Threshold', placeholder: 'Flag changes over 20%', required: false },
    ],
  },
  {
    id: 'social-scout', type: 'role', emoji: '📱', name: 'Social Scout',
    roleBadge: 'Social Monitoring',
    description: 'Monitors social mentions, competitor activity, and trending topics across platforms. Surfaces engagement opportunities and flags anything that needs a human response.',
    tags: ['social', 'monitoring', 'competitors', 'trends'],
    whatItDoes: [
      'Monitors social mentions of your brand 24/7',
      'Tracks competitor activity across platforms',
      'Surfaces engagement opportunities before they\'re missed',
      'Flags anything requiring urgent human response',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'platforms', label: 'Platforms to Monitor', placeholder: 'Instagram\nTwitter/X\nLinkedIn\nTikTok', required: false, type: 'textarea' },
      { key: 'competitors_to_track', label: 'Competitors to Track', placeholder: 'Competitor A (@handle)\nCompetitor B (@handle)', required: false, type: 'textarea' },
      { key: 'keywords', label: 'Keywords to Watch', placeholder: 'your brand name\nindustry terms\nproduct names', required: false, type: 'textarea' },
      { key: 'alert_urgency', label: 'Alert Urgency Rules', placeholder: 'Negative reviews → urgent\nCompetitor launch → high\nTrending topic → medium', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'brand-voice', type: 'role', emoji: '🛡️', name: 'Brand Voice Guard',
    roleBadge: 'Content Review',
    description: 'Reviews content for brand consistency — tone, messaging, vocabulary. Catches off-brand language before it goes public and suggests on-brand alternatives with specific fixes.',
    tags: ['content', 'branding', 'review', 'consistency'],
    whatItDoes: [
      'Reviews content for brand consistency before publishing',
      'Catches off-brand language and suggests alternatives',
      'Enforces vocabulary rules and messaging pillars',
      'Provides specific line-by-line fixes with explanations',
    ],
    channels: ['chat'],
    tools: ['Reviews Content'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'brand_tone', label: 'Brand Tone', placeholder: 'Professional but approachable. Never use slang. Always use inclusive language.', required: false, type: 'textarea' },
      { key: 'forbidden_words', label: 'Forbidden Words/Phrases', placeholder: 'synergy\nleverage\ngame-changer\ndisrupt', required: false, type: 'textarea' },
      { key: 'messaging_pillars', label: 'Messaging Pillars', placeholder: 'Innovation\nTrust\nSimplicity', required: false, type: 'textarea' },
      { key: 'approved_vocabulary', label: 'Approved Vocabulary', placeholder: 'Use "team members" not "employees"\nUse "clients" not "customers"', required: false, type: 'textarea' },
    ],
  },

  // ── GROUP A: Customer-Facing ──────────────────────────────────────────────

  {
    id: 'whatsapp-support', type: 'role', emoji: '💬', name: 'WhatsApp Support',
    roleBadge: 'Multi-Channel Support',
    description: 'Handles WhatsApp and SMS inquiries, qualifies leads, books appointments, and escalates complex issues — so you never miss a customer message.',
    tags: ['support', 'leads', 'qualification', 'booking', 'multi-channel'],
    whatItDoes: [
      'Responds to customer inquiries within seconds across WhatsApp and SMS',
      'Qualifies leads with discovery questions and scores their intent',
      'Books appointments and sends confirmation details',
      'Escalates complex issues to the owner with full conversation context',
    ],
    channels: ['sms', 'chat', 'telegram'],
    tools: ['Books Appointments', 'Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'business_hours', label: 'Business Hours', placeholder: 'Mon-Fri 9am-5pm EST', required: false },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team', required: false },
      { key: 'owner_name', label: 'Owner Name', placeholder: 'John Smith', required: false },
      { key: 'services', label: 'Services Offered', placeholder: 'Web design, SEO, paid ads, social media management', required: false },
      { key: 'faq_topics', label: 'FAQ Topics & Answers', placeholder: 'What are your hours? → Mon-Fri 9am-5pm\nDo you offer refunds? → Yes, within 30 days', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'phone-receptionist', type: 'role', emoji: '📞', name: 'Phone Receptionist',
    roleBadge: 'Voice Call Handling',
    description: 'Answers inbound calls professionally, routes to the right person, books appointments, and handles FAQs — 24/7 without putting callers on hold.',
    tags: ['voice', 'scheduling', 'FAQ', 'reception'],
    whatItDoes: [
      'Greets callers and identifies their needs through natural conversation',
      'Books and confirms appointments with date, time, and prep instructions',
      'Answers FAQs about hours, location, services, and pricing',
      'Escalates billing disputes and complaints to a human immediately',
    ],
    channels: ['voice', 'sms'],
    tools: ['Books Appointments', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'business_phone', label: 'Business Phone', placeholder: '+1 (555) 123-4567', required: false },
      { key: 'business_hours', label: 'Business Hours', placeholder: 'Mon-Fri 9am-5pm EST', required: false },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team', required: false },
      { key: 'services', label: 'Services Offered', placeholder: 'Haircuts, coloring, styling, treatments', required: false },
    ],
  },
  {
    id: 'sdr-outbound', type: 'role', emoji: '🎯', name: 'SDR Outbound',
    roleBadge: 'Sales Prospecting',
    description: 'Researches target accounts, drafts personalized cold outreach, and builds multi-touch sequences that turn cold contacts into warm conversations.',
    tags: ['leads', 'outreach', 'prospecting', 'sales', 'email'],
    whatItDoes: [
      'Researches prospects and identifies decision-makers from public data',
      'Drafts personalized cold emails under 120 words with a unique angle per prospect',
      'Builds 5-touch follow-up sequences (email → LinkedIn → breakup)',
      'Tracks reply rates and adjusts messaging based on what works',
    ],
    channels: ['chat', 'sms'],
    tools: ['Tags Contacts', 'Creates Deals', 'Web Search'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'target_persona', label: 'Target Persona', placeholder: 'VP of Marketing at B2B SaaS companies, 50-200 employees', required: false, type: 'textarea' },
      { key: 'ideal_customer_profile', label: 'Ideal Customer Profile', placeholder: 'B2B SaaS, $5M-$50M ARR, US-based, using HubSpot', required: false, type: 'textarea' },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team/discovery', required: false },
    ],
  },
  {
    id: 'objection-handler', type: 'role', emoji: '🗣️', name: 'Objection Handler',
    roleBadge: 'Sales Coaching',
    description: 'Provides instant rebuttals and talk tracks for every sales objection — price, timing, competition, authority — with 3 response options per objection.',
    tags: ['sales', 'coaching', 'objections', 'training'],
    whatItDoes: [
      'Classifies objections by category (price, timing, competition, authority, need)',
      'Generates 3 response options per objection so reps pick what fits their style',
      'Always includes a discovery question to keep the conversation going',
      'Coaches tone: never dismiss the objection, always acknowledge first',
    ],
    channels: ['chat'],
    tools: ['Reviews Content'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'product_name', label: 'Product Name', placeholder: 'Acme CRM Pro', required: false },
      { key: 'main_competitors', label: 'Main Competitors', placeholder: 'HubSpot — broader but less specialized\nSalesforce — enterprise, we\'re SMB-focused', required: false, type: 'textarea' },
      { key: 'key_differentiators', label: 'Key Differentiators', placeholder: '3x faster onboarding\nDedicated account manager\nNo annual contract required', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'nps-recovery', type: 'role', emoji: '⭐', name: 'NPS Recovery',
    roleBadge: 'Customer Retention',
    description: 'Follows up with NPS detractors using personalized, empathetic messages that acknowledge their specific concerns and offer concrete resolution paths.',
    tags: ['retention', 'NPS', 'support', 'recovery'],
    whatItDoes: [
      'Drafts personalized follow-up messages referencing the specific feedback given',
      'Identifies root cause category (product, support, pricing, onboarding)',
      'Connects customers with the right team or resource',
      'Tracks recovery rate and feeds systemic issues to leadership',
    ],
    channels: ['sms', 'chat', 'telegram'],
    tools: ['Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'owner_name', label: 'Owner Name', placeholder: 'John Smith', required: false },
      { key: 'support_email', label: 'Support Email', placeholder: 'support@acme.com', required: false },
      { key: 'response_sla', label: 'Response SLA', placeholder: 'Within 4 hours during business hours', required: false },
    ],
  },
  {
    id: 'abandoned-cart', type: 'role', emoji: '🛒', name: 'Abandoned Cart',
    roleBadge: 'E-Commerce Recovery',
    description: 'Sends timed, personalized cart recovery sequences at 1hr, 24hr, and 72hr intervals — with urgency copy, discount codes, and conversion tracking.',
    tags: ['ecommerce', 'recovery', 'email', 'conversion'],
    whatItDoes: [
      'Triggers personalized recovery messages at 1hr, 24hr, and 72hr after abandonment',
      'Segments carts by value, product type, and customer history',
      'Generates urgency-driven copy (low stock, expiring discounts)',
      'Tracks recovery rate and revenue recaptured per campaign',
    ],
    channels: ['sms', 'chat'],
    tools: ['Tags Contacts', 'Sends Messages'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'discount_code', label: 'Discount Code', placeholder: 'COMEBACK10', required: false },
      { key: 'cart_expiry_hours', label: 'Cart Expiry (hours)', placeholder: '72', required: false },
      { key: 'recovery_email', label: 'Recovery Email', placeholder: 'orders@acme.com', required: false },
    ],
  },
  {
    id: 'review-responder', type: 'role', emoji: '⭐', name: 'Review Responder',
    roleBadge: 'Reputation Management',
    description: 'Drafts personalized responses to 1-5 star reviews, escalates safety issues, and delivers weekly sentiment summaries to catch recurring problems early.',
    tags: ['reviews', 'reputation', 'content', 'support'],
    whatItDoes: [
      'Drafts personalized review responses in brand voice within 4 hours',
      'Detects urgent issues (defects, safety, legal threats) and escalates immediately',
      'Tracks sentiment trends and identifies recurring complaints',
      'Delivers weekly review digest: volume, average rating, top issues',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'brand_tone', label: 'Brand Tone', placeholder: 'Warm, professional, empathetic. Never defensive.', required: false, type: 'textarea' },
      { key: 'support_email', label: 'Support Email', placeholder: 'support@acme.com', required: false },
      { key: 'escalation_contact', label: 'Escalation Contact', placeholder: 'manager@acme.com', required: false },
    ],
  },
  {
    id: 'cold-outreach', type: 'role', emoji: '📨', name: 'Cold Outreach',
    roleBadge: 'B2B Prospecting',
    description: 'Finds leads matching your ICP, crafts personalized first-touch messages, and manages 4-step sequences across email and LinkedIn — without sounding robotic.',
    tags: ['leads', 'outreach', 'prospecting', 'B2B', 'email'],
    whatItDoes: [
      'Identifies prospects matching your ideal customer profile from public signals',
      'Crafts personalized first lines based on recent news, posts, or company activity',
      'Manages multi-step sequences with value-add follow-ups (never just "bumping this")',
      'Tracks sent, opened, replied metrics and optimizes messaging weekly',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Tags Contacts', 'Creates Deals'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'icp_title', label: 'ICP Job Titles', placeholder: 'CEO, Founder, VP of Marketing at agencies with 5-50 employees', required: false, type: 'textarea' },
      { key: 'icp_industry', label: 'ICP Industry', placeholder: 'Digital marketing agencies', required: false },
      { key: 'icp_company_size', label: 'ICP Company Size', placeholder: '5-50 employees', required: false },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team/discovery', required: false },
    ],
  },

  // ── GROUP B: Agency Deliverables ──────────────────────────────────────────

  {
    id: 'social-media-manager', type: 'role', emoji: '📱', name: 'Social Media Manager',
    roleBadge: 'Content & Scheduling',
    description: 'Writes platform-native posts for Twitter, LinkedIn, and Instagram, plans weekly content calendars, and tracks what performs so you can do more of it.',
    tags: ['content', 'social', 'scheduling', 'marketing'],
    whatItDoes: [
      'Writes posts adapted to each platform — punchy for Twitter, story-driven for LinkedIn',
      'Plans weekly content calendar with mix of educational, promotional, and personal',
      'Drafts replies to comments and identifies conversations worth joining',
      'Generates weekly performance report: impressions, engagement, top content',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'brand_tone', label: 'Brand Tone', placeholder: 'Professional but witty. Educational over promotional.', required: false, type: 'textarea' },
      { key: 'content_pillars', label: 'Content Pillars', placeholder: 'Industry insights\nProduct tips\nCustomer stories\nBehind the scenes', required: false, type: 'textarea' },
      { key: 'posting_frequency', label: 'Posting Frequency', placeholder: '3x/week Twitter, 2x/week LinkedIn, daily Instagram stories', required: false },
    ],
  },
  {
    id: 'brand-monitor', type: 'role', emoji: '👁️', name: 'Brand Monitor',
    roleBadge: 'Reputation Tracking',
    description: 'Watches for brand mentions across social platforms, flags negative sentiment, surfaces engagement opportunities, and delivers daily digests.',
    tags: ['social', 'monitoring', 'reputation', 'alerts'],
    whatItDoes: [
      'Monitors brand mentions across Twitter, Reddit, LinkedIn, and news',
      'Flags negative sentiment and competitor comparisons for immediate response',
      'Surfaces positive mentions worth amplifying or engaging with',
      'Delivers daily digest: total mentions, sentiment breakdown, top posts',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Web Search', 'Sends Alerts'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'brand_keywords', label: 'Brand Keywords', placeholder: 'Acme Corp\nacmecorp\n@acmecorp\n#acme', required: false, type: 'textarea' },
      { key: 'competitors', label: 'Competitors', placeholder: 'Competitor A\nCompetitor B', required: false, type: 'textarea' },
      { key: 'alert_threshold', label: 'Alert Threshold', placeholder: 'Negative sentiment or 5+ mentions in 1 hour', required: false },
    ],
  },
  {
    id: 'email-sequence', type: 'role', emoji: '📧', name: 'Email Sequence',
    roleBadge: 'Lead Nurturing',
    description: 'Writes multi-step drip campaigns with strong subject lines, value-add content at each step, and clear CTAs — no generic "just checking in" follow-ups.',
    tags: ['email', 'nurturing', 'leads', 'content', 'marketing'],
    whatItDoes: [
      'Writes 5-7 step email sequences with escalating value per touch',
      'Crafts subject lines under 5 words that get opened',
      'Adapts tone from educational to conversion-focused as sequence progresses',
      'Generates A/B variants for subject lines and CTAs',
    ],
    channels: ['chat'],
    tools: ['Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'sequence_goal', label: 'Sequence Goal', placeholder: 'Convert free trial users to paid plans', required: false },
      { key: 'target_persona', label: 'Target Persona', placeholder: 'SaaS founders who signed up for a free trial but haven\'t activated', required: false, type: 'textarea' },
      { key: 'cta_url', label: 'CTA URL', placeholder: 'https://app.acme.com/upgrade', required: false },
    ],
  },
  {
    id: 'content-repurposer', type: 'role', emoji: '♻️', name: 'Content Repurposer',
    roleBadge: 'Content Distribution',
    description: 'Takes one piece of content and converts it into platform-native formats: Twitter threads, LinkedIn posts, newsletter snippets, and video scripts.',
    tags: ['content', 'social', 'distribution', 'marketing'],
    whatItDoes: [
      'Converts blog posts into Twitter threads, LinkedIn posts, and newsletter snippets',
      'Adapts tone and format for each platform (not just copy-paste)',
      'Generates short-form video scripts from long-form articles',
      'Extracts 5-10 quotable moments per piece for social sharing',
    ],
    channels: ['chat'],
    tools: ['Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'brand_voice', label: 'Brand Voice', placeholder: 'Authoritative but approachable. Data-driven. No jargon.', required: false, type: 'textarea' },
      { key: 'primary_platform', label: 'Primary Platform', placeholder: 'LinkedIn', required: false },
      { key: 'secondary_platforms', label: 'Secondary Platforms', placeholder: 'Twitter\nInstagram\nNewsletter\nYouTube Shorts', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'competitor-intelligence', type: 'role', emoji: '🔭', name: 'Competitor Intelligence',
    roleBadge: 'Market Research',
    description: 'Tracks competitor pricing, product updates, job postings, and content — and delivers weekly reports on what changed and what it means.',
    tags: ['research', 'competitors', 'reports', 'analytics'],
    whatItDoes: [
      'Tracks competitor pricing changes and product announcements daily',
      'Analyzes competitor job postings to infer strategic priorities',
      'Monitors competitor social and content for positioning shifts',
      'Delivers weekly brief: changes detected, so-what analysis, recommended responses',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Web Search', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'competitors', label: 'Competitors', placeholder: 'Competitor A — https://competitor-a.com\nCompetitor B — https://competitor-b.com', required: false, type: 'textarea' },
      { key: 'tracking_keywords', label: 'Tracking Keywords', placeholder: 'pricing change\nnew feature\nfunding round\nhiring', required: false, type: 'textarea' },
      { key: 'alert_frequency', label: 'Alert Frequency', placeholder: 'Weekly digest + immediate alerts for major changes', required: false },
    ],
  },
  {
    id: 'seo-writer', type: 'role', emoji: '🔍', name: 'SEO Content Writer',
    roleBadge: 'Organic Growth',
    description: 'Writes SEO-optimized content based on real keyword data, structures it for featured snippets, and optimizes existing content for rankings.',
    tags: ['seo', 'content', 'marketing', 'writing'],
    whatItDoes: [
      'Researches target keywords and maps content to search intent',
      'Writes SEO-optimized articles with proper H1/H2 structure',
      'Optimizes existing content for featured snippets and People Also Ask',
      'Generates meta titles and descriptions under character limits',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'target_industry', label: 'Target Industry', placeholder: 'Digital marketing', required: false },
      { key: 'target_location', label: 'Target Location', placeholder: 'Austin, TX', required: false },
      { key: 'primary_keywords', label: 'Primary Keywords', placeholder: 'AI marketing tools\nautomated lead generation\nSMB CRM software', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'newsletter-curator', type: 'role', emoji: '📬', name: 'Newsletter Curator',
    roleBadge: 'Email Marketing',
    description: 'Curates the best industry content, writes weekly newsletter editions with your voice, and tracks open rates to continuously improve.',
    tags: ['newsletter', 'email', 'content', 'curation'],
    whatItDoes: [
      'Scans RSS feeds, Twitter, and industry sources for relevant content weekly',
      'Writes newsletter editions with editorial voice — not just link dumps',
      'Generates 3 subject line options per edition with predicted open rates',
      'Tracks performance and adjusts content mix based on click data',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'newsletter_niche', label: 'Newsletter Niche', placeholder: 'AI and automation for small business', required: false },
      { key: 'audience_description', label: 'Audience Description', placeholder: 'SMB owners and marketing managers interested in AI tools', required: false },
      { key: 'sending_day', label: 'Sending Day', placeholder: 'Tuesday', required: false },
    ],
  },

  // ── GROUP C: Industry Verticals ───────────────────────────────────────────

  {
    id: 'real-estate-qualifier', type: 'role', emoji: '🏠', name: 'Real Estate Lead Qualifier',
    roleBadge: 'Real Estate',
    description: 'Qualifies buyer and seller leads, collects property preferences, pre-qualifies financing, and routes hot leads to the agent before they go cold.',
    tags: ['leads', 'qualification', 'real-estate', 'booking'],
    whatItDoes: [
      'Qualifies buyer leads: timeline, pre-approval status, price range, must-haves',
      'Qualifies seller leads: motivation, timeline, property condition, price expectations',
      'Books property tours and listing consultations automatically',
      'Routes hot leads to agent immediately with full qualification summary',
    ],
    channels: ['sms', 'chat', 'voice'],
    tools: ['Books Appointments', 'Tags Contacts', 'Creates Deals', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Realty', required: false },
      { key: 'agent_name', label: 'Agent Name', placeholder: 'Sarah Johnson', required: false },
      { key: 'service_area', label: 'Service Area', placeholder: 'Austin, TX metro area', required: false },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team', required: false },
    ],
  },
  {
    id: 'wellness-receptionist', type: 'role', emoji: '🧘', name: 'Wellness Receptionist',
    roleBadge: 'Healthcare & Wellness',
    description: 'Handles appointment scheduling for wellness businesses — spas, chiropractors, gyms, therapists — with intake pre-screening and HIPAA-aware responses.',
    tags: ['scheduling', 'healthcare', 'intake', 'booking'],
    whatItDoes: [
      'Books wellness appointments with service selection and duration',
      'Pre-screens new patients with intake questions before their visit',
      'Answers FAQs about services, pricing, insurance, and cancellation policy',
      'Never provides medical diagnoses — always recommends professional consultation',
    ],
    channels: ['sms', 'chat', 'voice'],
    tools: ['Books Appointments', 'Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Serenity Wellness Center', required: false },
      { key: 'services', label: 'Services Offered', placeholder: 'Deep tissue massage — 60min\nSwedish massage — 90min\nAcupuncture — 45min', required: false, type: 'textarea' },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-team', required: false },
      { key: 'cancellation_policy', label: 'Cancellation Policy', placeholder: '24-hour cancellation required. Late cancellations charged 50%.', required: false },
      { key: 'intake_questions', label: 'Intake Questions', placeholder: 'Any current injuries?\nAre you pregnant?\nAllergies to oils or lotions?', required: false, type: 'textarea' },
    ],
  },
  {
    id: 'restaurant-host', type: 'role', emoji: '🍽️', name: 'Restaurant Host',
    roleBadge: 'Food & Beverage',
    description: 'Handles reservations, answers menu questions, manages waitlist, and handles special requests — so front-of-house can focus on in-person guests.',
    tags: ['scheduling', 'restaurant', 'hospitality', 'booking'],
    whatItDoes: [
      'Books reservations for any party size and notes special requests',
      'Answers questions about menu, dietary options, hours, and location',
      'Manages waitlist and sends hold/confirmation messages',
      'Handles special occasions: birthdays, anniversaries, private dining',
    ],
    channels: ['sms', 'chat', 'voice'],
    tools: ['Books Appointments', 'Tags Contacts'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Bella Cucina', required: false },
      { key: 'restaurant_name', label: 'Restaurant Name', placeholder: 'Bella Cucina Italian Kitchen', required: false },
      { key: 'business_hours', label: 'Business Hours', placeholder: 'Tue-Sun 5pm-10pm, closed Mondays', required: false },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://resy.com/your-restaurant', required: false },
      { key: 'max_party_size', label: 'Max Party Size', placeholder: '12', required: false },
      { key: 'cuisine_type', label: 'Cuisine Type', placeholder: 'Italian', required: false },
    ],
  },
  {
    id: 'ecommerce-support', type: 'role', emoji: '📦', name: 'E-Commerce Support',
    roleBadge: 'Retail & E-Commerce',
    description: 'Handles order status, returns, shipping questions, and product inquiries — reducing support volume by 60% while keeping customer satisfaction high.',
    tags: ['support', 'ecommerce', 'returns', 'shipping'],
    whatItDoes: [
      'Answers order status, shipping, and delivery questions instantly',
      'Handles return and exchange requests per company policy',
      'Answers product questions using knowledge base',
      'Escalates damaged/lost orders and complaints to human support',
    ],
    channels: ['sms', 'chat', 'telegram'],
    tools: ['Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Store', required: false },
      { key: 'return_policy', label: 'Return Policy', placeholder: '30-day returns, free shipping on exchanges, refund within 5-7 business days', required: false, type: 'textarea' },
      { key: 'shipping_policy', label: 'Shipping Policy', placeholder: 'Free shipping over $50. Standard 3-5 days. Express 1-2 days.', required: false, type: 'textarea' },
      { key: 'support_email', label: 'Support Email', placeholder: 'support@acme.com', required: false },
      { key: 'escalation_contact', label: 'Escalation Contact', placeholder: 'manager@acme.com', required: false },
    ],
  },
  {
    id: 'legal-intake', type: 'role', emoji: '⚖️', name: 'Legal Intake Specialist',
    roleBadge: 'Legal Services',
    description: 'Pre-qualifies potential clients, collects case details, and books consultations — while making clear the AI is not providing legal advice.',
    tags: ['legal', 'intake', 'qualification', 'booking'],
    whatItDoes: [
      'Pre-qualifies leads by practice area, jurisdiction, and timeline',
      'Collects case details through structured intake questions',
      'Books consultation appointments with the appropriate attorney',
      'Always clarifies: AI is not providing legal advice, attorney consultation required',
    ],
    channels: ['sms', 'chat', 'voice'],
    tools: ['Books Appointments', 'Tags Contacts', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Smith & Associates Law', required: false },
      { key: 'firm_name', label: 'Firm Name', placeholder: 'Smith & Associates', required: false },
      { key: 'practice_areas', label: 'Practice Areas', placeholder: 'Personal injury\nFamily law\nEstate planning\nBusiness litigation', required: false, type: 'textarea' },
      { key: 'booking_url', label: 'Booking URL', placeholder: 'https://calendly.com/your-firm/consultation', required: false },
      { key: 'disclaimer_text', label: 'Disclaimer Text', placeholder: 'This is not legal advice. For legal counsel, please schedule a consultation with one of our attorneys.', required: false, type: 'textarea' },
    ],
  },

  // ── GROUP D: Internal Operations ──────────────────────────────────────────

  {
    id: 'pipeline-tracker', type: 'role', emoji: '💼', name: 'Pipeline Tracker',
    roleBadge: 'Sales Operations',
    description: 'Scores leads by engagement, identifies hot prospects ready for outreach, flags deals going cold, and delivers weekly pipeline reports with revenue forecasts.',
    tags: ['crm', 'leads', 'reports', 'analytics', 'sales'],
    whatItDoes: [
      'Scores leads by engagement signals: page views, email opens, feature usage',
      'Identifies hot leads and recommends personalized outreach timing',
      'Flags deals going cold with suggested re-engagement messages',
      'Delivers weekly pipeline report: new leads, active deals, closed, forecast',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Creates Deals', 'Tags Contacts', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'crm_platform', label: 'CRM Platform', placeholder: 'GoHighLevel', required: false },
      { key: 'pipeline_stages', label: 'Pipeline Stages', placeholder: 'New Lead → Qualified → Proposal → Negotiation → Closed Won / Lost', required: false, type: 'textarea' },
      { key: 'hot_lead_threshold', label: 'Hot Lead Threshold', placeholder: 'Score 80+ or 3+ site visits in 7 days', required: false },
    ],
  },
  {
    id: 'churn-sentinel', type: 'role', emoji: '🔮', name: 'Churn Sentinel',
    roleBadge: 'Customer Retention',
    description: 'Detects at-risk customers from behavioral signals, scores churn risk, and triggers retention actions before customers cancel.',
    tags: ['retention', 'analytics', 'alerts', 'crm'],
    whatItDoes: [
      'Monitors engagement signals: login frequency, feature usage, support tickets',
      'Scores churn risk from 1-10 with explanation of driving factors',
      'Triggers personalized retention outreach at 7-day warning',
      'Reports weekly: at-risk accounts, churn probability, recommended actions',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Tags Contacts', 'Sends Alerts', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'risk_threshold', label: 'Risk Threshold', placeholder: 'Score 7+ out of 10 triggers intervention', required: false },
      { key: 'retention_offer', label: 'Retention Offer', placeholder: '20% discount for 3 months, free onboarding session, dedicated CSM', required: false, type: 'textarea' },
      { key: 'csm_contact', label: 'CSM Contact', placeholder: 'csm@acme.com', required: false },
    ],
  },
  {
    id: 'revenue-analyst', type: 'role', emoji: '📈', name: 'Revenue Analyst',
    roleBadge: 'Business Analytics',
    description: 'Analyzes MRR, churn, LTV, and conversion rates — and delivers weekly reports with specific recommendations, not just charts.',
    tags: ['analytics', 'reports', 'revenue', 'metrics'],
    whatItDoes: [
      'Calculates MRR, ARR, churn rate, and LTV from available data',
      'Identifies revenue trends and flags anomalies week-over-week',
      'Benchmarks metrics against industry standards for context',
      'Delivers weekly report: numbers first, insights second, recommendations third',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Creates Reports', 'Web Search'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'reporting_frequency', label: 'Reporting Frequency', placeholder: 'Weekly', required: false },
      { key: 'key_metrics', label: 'Key Metrics', placeholder: 'MRR\nChurn rate\nLTV\nCAC\nConversion rate', required: false, type: 'textarea' },
      { key: 'team_channel', label: 'Team Channel', placeholder: '#revenue-updates', required: false },
    ],
  },
  {
    id: 'meeting-scheduler', type: 'role', emoji: '📅', name: 'Meeting Scheduler',
    roleBadge: 'Scheduling',
    description: 'Handles cross-timezone scheduling, proposes available slots, sends calendar invites, and manages rescheduling requests — without the email tennis.',
    tags: ['scheduling', 'calendar', 'meetings', 'productivity'],
    whatItDoes: [
      "Proposes 3 available time slots adjusted for all attendees' timezones",
      'Sends calendar invites with agenda and meeting details',
      'Handles reschedule requests gracefully with alternative options',
      'Sends 24-hour reminders and meeting prep notes',
    ],
    channels: ['chat', 'sms'],
    tools: ['Books Appointments', 'Sends Messages'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'owner_name', label: 'Owner Name', placeholder: 'John Smith', required: false },
      { key: 'calendar_url', label: 'Calendar URL', placeholder: 'https://calendly.com/your-team', required: false },
      { key: 'meeting_duration_options', label: 'Meeting Duration Options', placeholder: '15min quick sync\n30min standard\n60min deep dive', required: false },
      { key: 'timezone', label: 'Timezone', placeholder: 'US/Eastern', required: false },
    ],
  },
  {
    id: 'client-reporter', type: 'role', emoji: '📊', name: 'Client Reporter',
    roleBadge: 'Agency Reporting',
    description: "Generates professional client performance reports with metrics, wins, and next steps — so agencies can send value-packed updates without hours of work.",
    tags: ['reports', 'analytics', 'agency', 'clients'],
    whatItDoes: [
      'Compiles metrics from connected tools into a structured report',
      'Highlights wins, improvements, and areas needing attention',
      "Generates client-ready language that's clear, not jargon-heavy",
      'Sends weekly report to client via email or Telegram automatically',
    ],
    channels: ['chat', 'telegram'],
    tools: ['Creates Reports', 'Sends Messages'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Agency', required: false },
      { key: 'client_name', label: 'Client Name', placeholder: 'Widget Co', required: false },
      { key: 'report_metrics', label: 'Report Metrics', placeholder: 'Leads generated\nAds spend\nConversion rate\nRevenue attributed\nROI', required: false, type: 'textarea' },
      { key: 'sending_day', label: 'Sending Day', placeholder: 'Friday', required: false },
      { key: 'client_email', label: 'Client Email', placeholder: 'client@widgetco.com', required: false },
    ],
  },
  {
    id: 'reddit-prospector', type: 'role', emoji: '🔎', name: 'Reddit Prospector',
    roleBadge: 'Social Listening',
    description: 'Monitors subreddits for "what tool should I use" threads, drafts contextual replies that mention your product naturally, and tracks response performance.',
    tags: ['social', 'prospecting', 'content', 'outreach'],
    whatItDoes: [
      'Monitors relevant subreddits for product recommendation requests',
      'Drafts context-aware replies that add value before mentioning your solution',
      'Flags competitor mentions and comparison threads for response',
      'Tracks which subreddits and comment styles drive the most traffic',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'product_name', label: 'Product Name', placeholder: 'Acme CRM', required: false },
      { key: 'target_subreddits', label: 'Target Subreddits', placeholder: 'r/smallbusiness\nr/SaaS\nr/marketing\nr/Entrepreneur', required: false, type: 'textarea' },
      { key: 'value_proposition', label: 'Value Proposition', placeholder: 'All-in-one CRM that replaces 5 tools for SMBs at half the cost', required: false },
    ],
  },
  {
    id: 'influencer-outreach', type: 'role', emoji: '🤝', name: 'Influencer Outreach',
    roleBadge: 'Creator Marketing',
    description: 'Finds relevant micro-influencers for your niche, evaluates fit by engagement rate and audience alignment, and drafts personalized partnership pitches.',
    tags: ['outreach', 'social', 'marketing', 'influencers'],
    whatItDoes: [
      'Identifies micro-influencers with high engagement in your target niche',
      'Evaluates fit: follower count, engagement rate, audience alignment',
      'Drafts personalized partnership pitches referencing their content',
      'Tracks outreach status and follows up with 3-touch sequence',
    ],
    channels: ['chat'],
    tools: ['Web Search', 'Tags Contacts', 'Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'target_niche', label: 'Target Niche', placeholder: 'SaaS productivity tools', required: false },
      { key: 'min_followers', label: 'Min Followers', placeholder: '5000', required: false },
      { key: 'max_followers', label: 'Max Followers', placeholder: '100000', required: false },
      { key: 'partnership_offer', label: 'Partnership Offer', placeholder: 'Free product access + 20% revenue share on referrals', required: false },
    ],
  },
  {
    id: 'data-analyst', type: 'role', emoji: '📊', name: 'Data Analyst',
    roleBadge: 'Business Intelligence',
    description: "Turns raw data into business insights — analyzes trends, spots anomalies, answers 'why did X happen' questions, and delivers clear summaries.",
    tags: ['analytics', 'reports', 'data', 'intelligence'],
    whatItDoes: [
      'Analyzes provided data and identifies key trends and patterns',
      'Answers specific business questions with data-backed explanations',
      'Flags anomalies and provides root cause hypotheses',
      'Summarizes findings in plain language with recommended actions',
    ],
    channels: ['chat'],
    tools: ['Creates Reports', 'Web Search'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'primary_metrics', label: 'Primary Metrics', placeholder: 'Revenue\nConversion rate\nUser signups\nChurn\nNPS score', required: false, type: 'textarea' },
      { key: 'reporting_period', label: 'Reporting Period', placeholder: 'Weekly', required: false },
    ],
  },
  {
    id: 'onboarding-guide', type: 'role', emoji: '🚀', name: 'Customer Onboarding Guide',
    roleBadge: 'Customer Success',
    description: 'Walks new customers through activation steps, checks in at key milestones, identifies stuck users, and hands off to support when needed.',
    tags: ['onboarding', 'support', 'retention', 'customer-success'],
    whatItDoes: [
      'Guides new customers through setup steps with personalized check-ins',
      'Tracks activation milestones and flags users who are stuck',
      'Answers product questions during the critical first 30 days',
      'Escalates high-touch accounts to CSM when churn risk is detected',
    ],
    channels: ['sms', 'chat', 'telegram'],
    tools: ['Tags Contacts', 'Sends Messages', 'Escalates to Human'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'product_name', label: 'Product Name', placeholder: 'Acme CRM', required: false },
      { key: 'activation_steps', label: 'Activation Steps', placeholder: '1. Create account\n2. Import contacts\n3. Set up first pipeline\n4. Send first campaign', required: false, type: 'textarea' },
      { key: 'csm_contact', label: 'CSM Contact', placeholder: 'csm@acme.com', required: false },
      { key: 'trial_length_days', label: 'Trial Length (days)', placeholder: '14', required: false },
    ],
  },
  {
    id: 'ab-test-analyst', type: 'role', emoji: '🧪', name: 'A/B Test Analyst',
    roleBadge: 'Growth & Optimization',
    description: 'Analyzes experiment results for statistical significance, segments by user cohort, and recommends what to ship — so growth decisions are data-driven.',
    tags: ['analytics', 'testing', 'growth', 'optimization'],
    whatItDoes: [
      'Calculates statistical significance and confidence intervals for A/B tests',
      'Segments results by user cohort, device, and traffic source',
      'Identifies which variant wins and explains the likely mechanism',
      'Recommends whether to ship, iterate, or abandon the experiment',
    ],
    channels: ['chat'],
    tools: ['Creates Reports'],
    variables: [
      { key: 'business_name', label: 'Business Name', placeholder: 'Acme Corp', required: false },
      { key: 'test_platform', label: 'Test Platform', placeholder: 'Optimizely', required: false },
      { key: 'significance_threshold', label: 'Significance Threshold', placeholder: '95%', required: false },
      { key: 'reporting_format', label: 'Reporting Format', placeholder: 'Executive summary with charts', required: false },
    ],
  },
];
