// Industry defaults for the Website Builder wizard
// Maps industry slugs to default services, branding, and config
//
// NOTE: nearbyCities are intentionally empty. The wizard's Step 3 has a
// custom city input where users enter their actual service areas. We removed
// all hardcoded city suggestions (Feb 2026) because they were tied to specific
// US metros and showed wrong cities for businesses in different regions.
// The user's entered city from Step 1 is auto-added as primary city.

export interface IndustryDefault {
  label: string;
  services: { name: string; slug: string }[];
  designStyle: string;
  colors: { primary: string; secondary: string };
  aiName: string;
  needsGeoPages: boolean;
  defaultPageCount: number;
  nearbyCities: string[];
}

export const INDUSTRY_DEFAULTS: Record<string, IndustryDefault> = {
  hvac: {
    label: 'HVAC',
    services: [
      { name: 'AC Repair', slug: 'ac-repair' },
      { name: 'Heating Repair', slug: 'heating-repair' },
      { name: 'AC Installation', slug: 'ac-installation' },
      { name: 'Furnace Installation', slug: 'furnace-installation' },
      { name: 'Duct Cleaning', slug: 'duct-cleaning' },
      { name: 'HVAC Maintenance', slug: 'hvac-maintenance' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#dc2626', secondary: '#111827' },
    aiName: 'Alex',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  plumbing: {
    label: 'Plumbing',
    services: [
      { name: 'Drain Cleaning', slug: 'drain-cleaning' },
      { name: 'Water Heater Repair', slug: 'water-heater-repair' },
      { name: 'Leak Detection', slug: 'leak-detection' },
      { name: 'Sewer Line Repair', slug: 'sewer-line-repair' },
      { name: 'Pipe Repair', slug: 'pipe-repair' },
      { name: 'Fixture Installation', slug: 'fixture-installation' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#2563eb', secondary: '#1e3a5f' },
    aiName: 'Sam',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  electrical: {
    label: 'Electrical',
    services: [
      { name: 'Electrical Repair', slug: 'electrical-repair' },
      { name: 'Panel Upgrade', slug: 'panel-upgrade' },
      { name: 'Outlet Installation', slug: 'outlet-installation' },
      { name: 'Lighting Installation', slug: 'lighting-installation' },
      { name: 'EV Charger Installation', slug: 'ev-charger-installation' },
      { name: 'Electrical Inspection', slug: 'electrical-inspection' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#f59e0b', secondary: '#1f2937' },
    aiName: 'Sparky',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  dental: {
    label: 'Dental',
    services: [
      { name: 'General Dentistry', slug: 'general-dentistry' },
      { name: 'Cosmetic Dentistry', slug: 'cosmetic-dentistry' },
      { name: 'Dental Implants', slug: 'dental-implants' },
      { name: 'Teeth Whitening', slug: 'teeth-whitening' },
      { name: 'Emergency Dentistry', slug: 'emergency-dentistry' },
      { name: 'Orthodontics', slug: 'orthodontics' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0d9488', secondary: '#f0fdfa' },
    aiName: 'Dana',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  legal: {
    label: 'Legal',
    services: [
      { name: 'Personal Injury', slug: 'personal-injury' },
      { name: 'Family Law', slug: 'family-law' },
      { name: 'Criminal Defense', slug: 'criminal-defense' },
      { name: 'Estate Planning', slug: 'estate-planning' },
      { name: 'Business Law', slug: 'business-law' },
      { name: 'Immigration', slug: 'immigration' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#b45309', secondary: '#1c1917' },
    aiName: 'James',
    needsGeoPages: true,
    defaultPageCount: 18,
    nearbyCities: [],
  },
  restaurant: {
    label: 'Restaurant',
    services: [
      { name: 'Dine-In', slug: 'dine-in' },
      { name: 'Takeout', slug: 'takeout' },
      { name: 'Catering', slug: 'catering' },
      { name: 'Private Events', slug: 'private-events' },
      { name: 'Delivery', slug: 'delivery' },
    ],
    designStyle: 'bold',
    colors: { primary: '#dc2626', secondary: '#1c1917' },
    aiName: 'Aria',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
  'real-estate': {
    label: 'Real Estate',
    services: [
      { name: 'Buying', slug: 'buying' },
      { name: 'Selling', slug: 'selling' },
      { name: 'Property Valuation', slug: 'property-valuation' },
      { name: 'Relocation', slug: 'relocation' },
      { name: 'Investment Properties', slug: 'investment-properties' },
      { name: 'First-Time Buyers', slug: 'first-time-buyers' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#4f46e5', secondary: '#eef2ff' },
    aiName: 'Riley',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  auto: {
    label: 'Auto / Mechanic',
    services: [
      { name: 'Oil Change', slug: 'oil-change' },
      { name: 'Brake Repair', slug: 'brake-repair' },
      { name: 'Engine Diagnostics', slug: 'engine-diagnostics' },
      { name: 'Transmission Repair', slug: 'transmission-repair' },
      { name: 'Tire Service', slug: 'tire-service' },
      { name: 'AC Repair', slug: 'auto-ac-repair' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#ef4444', secondary: '#18181b' },
    aiName: 'Max',
    needsGeoPages: true,
    defaultPageCount: 30,
    nearbyCities: [],
  },
  'med-spa': {
    label: 'Medical Spa',
    services: [
      { name: 'Botox', slug: 'botox' },
      { name: 'Dermal Fillers', slug: 'dermal-fillers' },
      { name: 'Laser Hair Removal', slug: 'laser-hair-removal' },
      { name: 'Chemical Peels', slug: 'chemical-peels' },
      { name: 'Microneedling', slug: 'microneedling' },
      { name: 'Body Contouring', slug: 'body-contouring' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#ec4899', secondary: '#831843' },
    aiName: 'Sophia',
    needsGeoPages: false,
    defaultPageCount: 18,
    nearbyCities: [],
  },
  fitness: {
    label: 'Fitness / Gym',
    services: [
      { name: 'Personal Training', slug: 'personal-training' },
      { name: 'Group Classes', slug: 'group-classes' },
      { name: 'Yoga', slug: 'yoga' },
      { name: 'CrossFit', slug: 'crossfit' },
      { name: 'Nutrition Coaching', slug: 'nutrition-coaching' },
    ],
    designStyle: 'bold',
    colors: { primary: '#7c3aed', secondary: '#1e1b4b' },
    aiName: 'Coach',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
  veterinary: {
    label: 'Veterinary',
    services: [
      { name: 'Wellness Exams', slug: 'wellness-exams' },
      { name: 'Vaccinations', slug: 'vaccinations' },
      { name: 'Surgery', slug: 'surgery' },
      { name: 'Dental Care', slug: 'dental-care' },
      { name: 'Emergency Care', slug: 'emergency-care' },
      { name: 'Grooming', slug: 'grooming' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#059669', secondary: '#ecfdf5' },
    aiName: 'Doc',
    needsGeoPages: false,
    defaultPageCount: 18,
    nearbyCities: [],
  },
  consulting: {
    label: 'Consulting',
    services: [
      { name: 'Strategy Consulting', slug: 'strategy-consulting' },
      { name: 'Operations', slug: 'operations' },
      { name: 'Digital Transformation', slug: 'digital-transformation' },
      { name: 'Marketing Strategy', slug: 'marketing-strategy' },
      { name: 'Financial Advisory', slug: 'financial-advisory' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#1e40af', secondary: '#1e3a5f' },
    aiName: 'Jordan',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
  roofing: {
    label: 'Roofing',
    services: [
      { name: 'Roof Repair', slug: 'roof-repair' },
      { name: 'Roof Replacement', slug: 'roof-replacement' },
      { name: 'Roof Inspection', slug: 'roof-inspection' },
      { name: 'Storm Damage Repair', slug: 'storm-damage-repair' },
      { name: 'Gutter Installation', slug: 'gutter-installation' },
      { name: 'Commercial Roofing', slug: 'commercial-roofing' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#b91c1c', secondary: '#1f2937' },
    aiName: 'Rex',
    needsGeoPages: true,
    defaultPageCount: 30,
    nearbyCities: [],
  },
  landscaping: {
    label: 'Landscaping',
    services: [
      { name: 'Landscape Design', slug: 'landscape-design' },
      { name: 'Hardscaping', slug: 'hardscaping' },
      { name: 'Tree Trimming', slug: 'tree-trimming' },
      { name: 'Irrigation Systems', slug: 'irrigation-systems' },
      { name: 'Sod Installation', slug: 'sod-installation' },
      { name: 'Outdoor Lighting', slug: 'outdoor-lighting' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#15803d', secondary: '#f0fdf4' },
    aiName: 'Luke',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  'lawn-care': {
    label: 'Lawn Care',
    services: [
      { name: 'Lawn Mowing', slug: 'lawn-mowing' },
      { name: 'Fertilization', slug: 'fertilization' },
      { name: 'Weed Control', slug: 'weed-control' },
      { name: 'Aeration', slug: 'aeration' },
      { name: 'Leaf Removal', slug: 'leaf-removal' },
      { name: 'Seasonal Cleanup', slug: 'seasonal-cleanup' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#16a34a', secondary: '#ecfdf5' },
    aiName: 'Buddy',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  cleaning: {
    label: 'Cleaning',
    services: [
      { name: 'House Cleaning', slug: 'house-cleaning' },
      { name: 'Deep Cleaning', slug: 'deep-cleaning' },
      { name: 'Move-In/Move-Out Cleaning', slug: 'move-in-move-out-cleaning' },
      { name: 'Office Cleaning', slug: 'office-cleaning' },
      { name: 'Post-Construction Cleaning', slug: 'post-construction-cleaning' },
      { name: 'Carpet Cleaning', slug: 'carpet-cleaning' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0891b2', secondary: '#ecfeff' },
    aiName: 'Clara',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  painting: {
    label: 'Painting',
    services: [
      { name: 'Interior Painting', slug: 'interior-painting' },
      { name: 'Exterior Painting', slug: 'exterior-painting' },
      { name: 'Cabinet Painting', slug: 'cabinet-painting' },
      { name: 'Deck Staining', slug: 'deck-staining' },
      { name: 'Pressure Washing', slug: 'pressure-washing' },
      { name: 'Commercial Painting', slug: 'commercial-painting' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#2563eb', secondary: '#eff6ff' },
    aiName: 'Pat',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  flooring: {
    label: 'Flooring',
    services: [
      { name: 'Hardwood Flooring', slug: 'hardwood-flooring' },
      { name: 'Tile Installation', slug: 'tile-installation' },
      { name: 'Carpet Installation', slug: 'carpet-installation' },
      { name: 'Laminate Flooring', slug: 'laminate-flooring' },
      { name: 'Vinyl Flooring', slug: 'vinyl-flooring' },
      { name: 'Floor Refinishing', slug: 'floor-refinishing' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#92400e', secondary: '#fef3c7' },
    aiName: 'Frank',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  remodeling: {
    label: 'Remodeling',
    services: [
      { name: 'Kitchen Remodeling', slug: 'kitchen-remodeling' },
      { name: 'Bathroom Remodeling', slug: 'bathroom-remodeling' },
      { name: 'Basement Finishing', slug: 'basement-finishing' },
      { name: 'Home Additions', slug: 'home-additions' },
      { name: 'Whole Home Remodel', slug: 'whole-home-remodel' },
      { name: 'Custom Cabinetry', slug: 'custom-cabinetry' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#d97706', secondary: '#1c1917' },
    aiName: 'Rob',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  'pest-control': {
    label: 'Pest Control',
    services: [
      { name: 'Termite Treatment', slug: 'termite-treatment' },
      { name: 'Rodent Control', slug: 'rodent-control' },
      { name: 'Bed Bug Treatment', slug: 'bed-bug-treatment' },
      { name: 'Ant Control', slug: 'ant-control' },
      { name: 'Mosquito Control', slug: 'mosquito-control' },
      { name: 'Wildlife Removal', slug: 'wildlife-removal' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#059669', secondary: '#111827' },
    aiName: 'Pete',
    needsGeoPages: true,
    defaultPageCount: 30,
    nearbyCities: [],
  },
  locksmith: {
    label: 'Locksmith',
    services: [
      { name: 'Emergency Lockout', slug: 'emergency-lockout' },
      { name: 'Lock Rekeying', slug: 'lock-rekeying' },
      { name: 'Lock Installation', slug: 'lock-installation' },
      { name: 'Car Lockout', slug: 'car-lockout' },
      { name: 'Key Duplication', slug: 'key-duplication' },
      { name: 'Safe Services', slug: 'safe-services' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#f59e0b', secondary: '#18181b' },
    aiName: 'Leo',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  moving: {
    label: 'Moving',
    services: [
      { name: 'Local Moving', slug: 'local-moving' },
      { name: 'Long Distance Moving', slug: 'long-distance-moving' },
      { name: 'Packing Services', slug: 'packing-services' },
      { name: 'Commercial Moving', slug: 'commercial-moving' },
      { name: 'Storage Solutions', slug: 'storage-solutions' },
      { name: 'Piano Moving', slug: 'piano-moving' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#4f46e5', secondary: '#eef2ff' },
    aiName: 'Mike',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  salon: {
    label: 'Salon / Beauty',
    services: [
      { name: 'Haircuts & Styling', slug: 'haircuts-styling' },
      { name: 'Hair Coloring', slug: 'hair-coloring' },
      { name: 'Manicure & Pedicure', slug: 'manicure-pedicure' },
      { name: 'Waxing', slug: 'waxing' },
      { name: 'Facials', slug: 'facials' },
      { name: 'Bridal Services', slug: 'bridal-services' },
    ],
    designStyle: 'bold',
    colors: { primary: '#be185d', secondary: '#831843' },
    aiName: 'Stella',
    needsGeoPages: false,
    defaultPageCount: 12,
    nearbyCities: [],
  },
  medical: {
    label: 'Medical / Healthcare',
    services: [
      { name: 'Primary Care', slug: 'primary-care' },
      { name: 'Urgent Care', slug: 'urgent-care' },
      { name: 'Physical Therapy', slug: 'physical-therapy' },
      { name: 'Chiropractic', slug: 'chiropractic' },
      { name: 'Pediatrics', slug: 'pediatrics' },
      { name: 'Telehealth', slug: 'telehealth' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0d9488', secondary: '#134e4a' },
    aiName: 'Dr. Kyra',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  accounting: {
    label: 'Accounting',
    services: [
      { name: 'Tax Preparation', slug: 'tax-preparation' },
      { name: 'Bookkeeping', slug: 'bookkeeping' },
      { name: 'Payroll Services', slug: 'payroll-services' },
      { name: 'Business Tax Planning', slug: 'business-tax-planning' },
      { name: 'Audit Support', slug: 'audit-support' },
      { name: 'Financial Statements', slug: 'financial-statements' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#1e3a5f', secondary: '#f8fafc' },
    aiName: 'Alex',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },

  // ── New Industries (Mar 26, 2026) ──────────────────────────────────────

  cannabis: {
    label: 'Cannabis / Dispensary',
    services: [
      { name: 'Flower', slug: 'flower' },
      { name: 'Edibles', slug: 'edibles' },
      { name: 'Concentrates', slug: 'concentrates' },
      { name: 'Pre-Rolls', slug: 'pre-rolls' },
      { name: 'Topicals', slug: 'topicals' },
      { name: 'Accessories', slug: 'accessories' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#16a34a', secondary: '#14532d' },
    aiName: 'Bud',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  contractor: {
    label: 'General Contractor',
    services: [
      { name: 'New Construction', slug: 'new-construction' },
      { name: 'Home Renovation', slug: 'home-renovation' },
      { name: 'Commercial Build-Out', slug: 'commercial-build-out' },
      { name: 'Permits & Planning', slug: 'permits-planning' },
      { name: 'Foundation Work', slug: 'foundation-work' },
      { name: 'Project Management', slug: 'project-management' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#d97706', secondary: '#1c1917' },
    aiName: 'Jake',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: [],
  },
  insurance: {
    label: 'Insurance',
    services: [
      { name: 'Auto Insurance', slug: 'auto-insurance' },
      { name: 'Home Insurance', slug: 'home-insurance' },
      { name: 'Life Insurance', slug: 'life-insurance' },
      { name: 'Business Insurance', slug: 'business-insurance' },
      { name: 'Health Insurance', slug: 'health-insurance' },
      { name: 'Umbrella Policy', slug: 'umbrella-policy' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#1e40af', secondary: '#eff6ff' },
    aiName: 'Sarah',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  photography: {
    label: 'Photography',
    services: [
      { name: 'Wedding Photography', slug: 'wedding-photography' },
      { name: 'Portrait Sessions', slug: 'portrait-sessions' },
      { name: 'Corporate Headshots', slug: 'corporate-headshots' },
      { name: 'Event Photography', slug: 'event-photography' },
      { name: 'Product Photography', slug: 'product-photography' },
      { name: 'Real Estate Photography', slug: 'real-estate-photography' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#1f2937', secondary: '#f9fafb' },
    aiName: 'Ava',
    needsGeoPages: false,
    defaultPageCount: 12,
    nearbyCities: [],
  },
  chiropractic: {
    label: 'Chiropractic',
    services: [
      { name: 'Spinal Adjustment', slug: 'spinal-adjustment' },
      { name: 'Sports Injury Treatment', slug: 'sports-injury' },
      { name: 'Sciatica Treatment', slug: 'sciatica-treatment' },
      { name: 'Neck Pain Relief', slug: 'neck-pain-relief' },
      { name: 'Posture Correction', slug: 'posture-correction' },
      { name: 'Wellness Programs', slug: 'wellness-programs' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0d9488', secondary: '#f0fdfa' },
    aiName: 'Dr. Kim',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  therapy: {
    label: 'Therapy / Counseling',
    services: [
      { name: 'Individual Therapy', slug: 'individual-therapy' },
      { name: 'Couples Counseling', slug: 'couples-counseling' },
      { name: 'Family Therapy', slug: 'family-therapy' },
      { name: 'Anxiety Treatment', slug: 'anxiety-treatment' },
      { name: 'Depression Support', slug: 'depression-support' },
      { name: 'Trauma / EMDR', slug: 'trauma-emdr' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#7c3aed', secondary: '#f5f3ff' },
    aiName: 'Maya',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  'pet-services': {
    label: 'Pet Services',
    services: [
      { name: 'Dog Grooming', slug: 'dog-grooming' },
      { name: 'Pet Boarding', slug: 'pet-boarding' },
      { name: 'Dog Walking', slug: 'dog-walking' },
      { name: 'Pet Sitting', slug: 'pet-sitting' },
      { name: 'Dog Training', slug: 'dog-training' },
      { name: 'Pet Daycare', slug: 'pet-daycare' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#ea580c', secondary: '#fff7ed' },
    aiName: 'Paws',
    needsGeoPages: false,
    defaultPageCount: 12,
    nearbyCities: [],
  },
  wedding: {
    label: 'Wedding / Events',
    services: [
      { name: 'Wedding Planning', slug: 'wedding-planning' },
      { name: 'Event Coordination', slug: 'event-coordination' },
      { name: 'Venue Decoration', slug: 'venue-decoration' },
      { name: 'Floral Design', slug: 'floral-design' },
      { name: 'DJ / Entertainment', slug: 'dj-entertainment' },
      { name: 'Corporate Events', slug: 'corporate-events' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#be185d', secondary: '#fdf2f8' },
    aiName: 'Grace',
    needsGeoPages: false,
    defaultPageCount: 12,
    nearbyCities: [],
  },
  mortgage: {
    label: 'Mortgage / Lending',
    services: [
      { name: 'Home Purchase Loans', slug: 'home-purchase-loans' },
      { name: 'Refinancing', slug: 'refinancing' },
      { name: 'FHA Loans', slug: 'fha-loans' },
      { name: 'VA Loans', slug: 'va-loans' },
      { name: 'Investment Property Loans', slug: 'investment-property-loans' },
      { name: 'Pre-Approval', slug: 'pre-approval' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#1e40af', secondary: '#f8fafc' },
    aiName: 'Mark',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  telecom: {
    label: 'Telecom / IT Services',
    services: [
      { name: 'POTS Replacement', slug: 'pots-replacement' },
      { name: 'Voice Solutions', slug: 'voice-solutions' },
      { name: 'Internet Connectivity', slug: 'internet-connectivity' },
      { name: 'Mobility Solutions', slug: 'mobility-solutions' },
      { name: 'Fleet Management', slug: 'fleet-management' },
      { name: 'IP-PBX', slug: 'ip-pbx' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#2563eb', secondary: '#1e3a5f' },
    aiName: 'Nex',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
};

export const DESIGN_STYLES = [
  { id: 'modern-dark', label: 'Modern Dark', description: 'Bold dark backgrounds with vibrant accents', preview: '🌙' },
  { id: 'clean-light', label: 'Clean Light', description: 'Crisp white layouts with subtle shadows', preview: '☀️' },
  { id: 'bold', label: 'Bold', description: 'Strong colors, large typography, high contrast', preview: '🔥' },
  { id: 'minimal', label: 'Minimal', description: 'Lots of whitespace, understated elegance', preview: '✨' },
] as const;

export const TONE_OPTIONS = [
  { id: 'professional', label: 'Professional', description: 'Polished and authoritative' },
  { id: 'friendly', label: 'Friendly', description: 'Warm and approachable' },
  { id: 'casual', label: 'Casual', description: 'Relaxed and conversational' },
] as const;

export const AI_CAPABILITIES = [
  { id: 'answer_questions', label: 'Answer questions about the business' },
  { id: 'book_appointments', label: 'Book appointments and schedule calls' },
  { id: 'capture_leads', label: 'Capture lead info (name, phone, email)' },
  { id: 'provide_quotes', label: 'Provide estimates and pricing info' },
  { id: 'qualify_leads', label: 'Qualify leads and assess urgency' },
] as const;

// Business hours time options for the wizard dropdown
export const BUSINESS_HOURS_OPTIONS = [
  '6:00 AM', '6:30 AM', '7:00 AM', '7:30 AM', '8:00 AM', '8:30 AM',
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '12:00 PM', '12:30 PM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM',
  '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM',
  '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM', '8:00 PM', '8:30 PM',
  '9:00 PM', '9:30 PM', '10:00 PM', '10:30 PM', '11:00 PM',
] as const;
