// Industry defaults for the Website Builder wizard
// Maps industry slugs to default services, branding, and config

export interface IndustryDefault {
  label: string;
  services: { name: string; slug: string }[];
  designStyle: string;
  colors: { primary: string; secondary: string };
  aiName: string;
  needsGeoPages: boolean;
  defaultPageCount: number;
  nearbyCities: string[];
}

export const INDUSTRY_DEFAULTS: Record<string, IndustryDefault> = {
  hvac: {
    label: 'HVAC',
    services: [
      { name: 'AC Repair', slug: 'ac-repair' },
      { name: 'Heating Repair', slug: 'heating-repair' },
      { name: 'AC Installation', slug: 'ac-installation' },
      { name: 'Furnace Installation', slug: 'furnace-installation' },
      { name: 'Duct Cleaning', slug: 'duct-cleaning' },
      { name: 'HVAC Maintenance', slug: 'hvac-maintenance' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#dc2626', secondary: '#111827' },
    aiName: 'Alex',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['San Mateo', 'Burlingame', 'Foster City', 'Redwood City', 'Belmont', 'San Carlos', 'Daly City', 'South San Francisco', 'Millbrae', 'Half Moon Bay'],
  },
  plumbing: {
    label: 'Plumbing',
    services: [
      { name: 'Drain Cleaning', slug: 'drain-cleaning' },
      { name: 'Water Heater Repair', slug: 'water-heater-repair' },
      { name: 'Leak Detection', slug: 'leak-detection' },
      { name: 'Sewer Line Repair', slug: 'sewer-line-repair' },
      { name: 'Pipe Repair', slug: 'pipe-repair' },
      { name: 'Fixture Installation', slug: 'fixture-installation' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#2563eb', secondary: '#1e3a5f' },
    aiName: 'Sam',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['San Jose', 'Sunnyvale', 'Santa Clara', 'Mountain View', 'Palo Alto', 'Cupertino', 'Milpitas', 'Fremont', 'Campbell', 'Los Gatos'],
  },
  electrical: {
    label: 'Electrical',
    services: [
      { name: 'Electrical Repair', slug: 'electrical-repair' },
      { name: 'Panel Upgrade', slug: 'panel-upgrade' },
      { name: 'Outlet Installation', slug: 'outlet-installation' },
      { name: 'Lighting Installation', slug: 'lighting-installation' },
      { name: 'EV Charger Installation', slug: 'ev-charger-installation' },
      { name: 'Electrical Inspection', slug: 'electrical-inspection' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#f59e0b', secondary: '#1f2937' },
    aiName: 'Sparky',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Oakland', 'Berkeley', 'Hayward', 'San Leandro', 'Alameda', 'Fremont', 'Union City', 'Newark', 'Pleasanton', 'Dublin'],
  },
  dental: {
    label: 'Dental',
    services: [
      { name: 'General Dentistry', slug: 'general-dentistry' },
      { name: 'Cosmetic Dentistry', slug: 'cosmetic-dentistry' },
      { name: 'Dental Implants', slug: 'dental-implants' },
      { name: 'Teeth Whitening', slug: 'teeth-whitening' },
      { name: 'Emergency Dentistry', slug: 'emergency-dentistry' },
      { name: 'Orthodontics', slug: 'orthodontics' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0d9488', secondary: '#f0fdfa' },
    aiName: 'Dana',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  legal: {
    label: 'Legal',
    services: [
      { name: 'Personal Injury', slug: 'personal-injury' },
      { name: 'Family Law', slug: 'family-law' },
      { name: 'Criminal Defense', slug: 'criminal-defense' },
      { name: 'Estate Planning', slug: 'estate-planning' },
      { name: 'Business Law', slug: 'business-law' },
      { name: 'Immigration', slug: 'immigration' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#b45309', secondary: '#1c1917' },
    aiName: 'James',
    needsGeoPages: true,
    defaultPageCount: 18,
    nearbyCities: ['Downtown', 'Midtown', 'Westside', 'Northside', 'Southside', 'East End', 'West End', 'Central', 'Uptown', 'Suburbs'],
  },
  restaurant: {
    label: 'Restaurant',
    services: [
      { name: 'Dine-In', slug: 'dine-in' },
      { name: 'Takeout', slug: 'takeout' },
      { name: 'Catering', slug: 'catering' },
      { name: 'Private Events', slug: 'private-events' },
      { name: 'Delivery', slug: 'delivery' },
    ],
    designStyle: 'bold',
    colors: { primary: '#dc2626', secondary: '#fef2f2' },
    aiName: 'Aria',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
  'real-estate': {
    label: 'Real Estate',
    services: [
      { name: 'Buying', slug: 'buying' },
      { name: 'Selling', slug: 'selling' },
      { name: 'Property Valuation', slug: 'property-valuation' },
      { name: 'Relocation', slug: 'relocation' },
      { name: 'Investment Properties', slug: 'investment-properties' },
      { name: 'First-Time Buyers', slug: 'first-time-buyers' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#4f46e5', secondary: '#eef2ff' },
    aiName: 'Riley',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Los Angeles', 'Beverly Hills', 'Santa Monica', 'Pasadena', 'Glendale', 'Burbank', 'Long Beach', 'Culver City', 'West Hollywood', 'Malibu'],
  },
  auto: {
    label: 'Auto / Mechanic',
    services: [
      { name: 'Oil Change', slug: 'oil-change' },
      { name: 'Brake Repair', slug: 'brake-repair' },
      { name: 'Engine Diagnostics', slug: 'engine-diagnostics' },
      { name: 'Transmission Repair', slug: 'transmission-repair' },
      { name: 'Tire Service', slug: 'tire-service' },
      { name: 'AC Repair', slug: 'auto-ac-repair' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#ef4444', secondary: '#18181b' },
    aiName: 'Max',
    needsGeoPages: true,
    defaultPageCount: 30,
    nearbyCities: ['Houston', 'Sugar Land', 'Katy', 'Pearland', 'Pasadena', 'The Woodlands', 'Spring', 'Cypress', 'Humble', 'Missouri City'],
  },
  'med-spa': {
    label: 'Medical Spa',
    services: [
      { name: 'Botox', slug: 'botox' },
      { name: 'Dermal Fillers', slug: 'dermal-fillers' },
      { name: 'Laser Hair Removal', slug: 'laser-hair-removal' },
      { name: 'Chemical Peels', slug: 'chemical-peels' },
      { name: 'Microneedling', slug: 'microneedling' },
      { name: 'Body Contouring', slug: 'body-contouring' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#ec4899', secondary: '#fdf2f8' },
    aiName: 'Sophia',
    needsGeoPages: false,
    defaultPageCount: 18,
    nearbyCities: [],
  },
  fitness: {
    label: 'Fitness / Gym',
    services: [
      { name: 'Personal Training', slug: 'personal-training' },
      { name: 'Group Classes', slug: 'group-classes' },
      { name: 'Yoga', slug: 'yoga' },
      { name: 'CrossFit', slug: 'crossfit' },
      { name: 'Nutrition Coaching', slug: 'nutrition-coaching' },
    ],
    designStyle: 'bold',
    colors: { primary: '#7c3aed', secondary: '#1e1b4b' },
    aiName: 'Coach',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
  veterinary: {
    label: 'Veterinary',
    services: [
      { name: 'Wellness Exams', slug: 'wellness-exams' },
      { name: 'Vaccinations', slug: 'vaccinations' },
      { name: 'Surgery', slug: 'surgery' },
      { name: 'Dental Care', slug: 'dental-care' },
      { name: 'Emergency Care', slug: 'emergency-care' },
      { name: 'Grooming', slug: 'grooming' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#059669', secondary: '#ecfdf5' },
    aiName: 'Doc',
    needsGeoPages: false,
    defaultPageCount: 18,
    nearbyCities: [],
  },
  consulting: {
    label: 'Consulting',
    services: [
      { name: 'Strategy Consulting', slug: 'strategy-consulting' },
      { name: 'Operations', slug: 'operations' },
      { name: 'Digital Transformation', slug: 'digital-transformation' },
      { name: 'Marketing Strategy', slug: 'marketing-strategy' },
      { name: 'Financial Advisory', slug: 'financial-advisory' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#1e40af', secondary: '#eff6ff' },
    aiName: 'Jordan',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
  roofing: {
    label: 'Roofing',
    services: [
      { name: 'Roof Repair', slug: 'roof-repair' },
      { name: 'Roof Replacement', slug: 'roof-replacement' },
      { name: 'Roof Inspection', slug: 'roof-inspection' },
      { name: 'Storm Damage Repair', slug: 'storm-damage-repair' },
      { name: 'Gutter Installation', slug: 'gutter-installation' },
      { name: 'Commercial Roofing', slug: 'commercial-roofing' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#b91c1c', secondary: '#1f2937' },
    aiName: 'Rex',
    needsGeoPages: true,
    defaultPageCount: 30,
    nearbyCities: ['Dallas', 'Fort Worth', 'Arlington', 'Plano', 'Irving', 'Garland', 'Frisco', 'McKinney', 'Denton', 'Mesquite'],
  },
  landscaping: {
    label: 'Landscaping',
    services: [
      { name: 'Landscape Design', slug: 'landscape-design' },
      { name: 'Hardscaping', slug: 'hardscaping' },
      { name: 'Tree Trimming', slug: 'tree-trimming' },
      { name: 'Irrigation Systems', slug: 'irrigation-systems' },
      { name: 'Sod Installation', slug: 'sod-installation' },
      { name: 'Outdoor Lighting', slug: 'outdoor-lighting' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#15803d', secondary: '#f0fdf4' },
    aiName: 'Luke',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Phoenix', 'Scottsdale', 'Tempe', 'Mesa', 'Chandler', 'Gilbert', 'Glendale', 'Peoria', 'Surprise', 'Goodyear'],
  },
  'lawn-care': {
    label: 'Lawn Care',
    services: [
      { name: 'Lawn Mowing', slug: 'lawn-mowing' },
      { name: 'Fertilization', slug: 'fertilization' },
      { name: 'Weed Control', slug: 'weed-control' },
      { name: 'Aeration', slug: 'aeration' },
      { name: 'Leaf Removal', slug: 'leaf-removal' },
      { name: 'Seasonal Cleanup', slug: 'seasonal-cleanup' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#16a34a', secondary: '#ecfdf5' },
    aiName: 'Buddy',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Atlanta', 'Marietta', 'Roswell', 'Alpharetta', 'Kennesaw', 'Smyrna', 'Decatur', 'Duluth', 'Lawrenceville', 'Suwanee'],
  },
  cleaning: {
    label: 'Cleaning',
    services: [
      { name: 'House Cleaning', slug: 'house-cleaning' },
      { name: 'Deep Cleaning', slug: 'deep-cleaning' },
      { name: 'Move-In/Move-Out Cleaning', slug: 'move-in-move-out-cleaning' },
      { name: 'Office Cleaning', slug: 'office-cleaning' },
      { name: 'Post-Construction Cleaning', slug: 'post-construction-cleaning' },
      { name: 'Carpet Cleaning', slug: 'carpet-cleaning' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0891b2', secondary: '#ecfeff' },
    aiName: 'Clara',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Chicago', 'Evanston', 'Oak Park', 'Naperville', 'Schaumburg', 'Arlington Heights', 'Skokie', 'Cicero', 'Berwyn', 'Des Plaines'],
  },
  painting: {
    label: 'Painting',
    services: [
      { name: 'Interior Painting', slug: 'interior-painting' },
      { name: 'Exterior Painting', slug: 'exterior-painting' },
      { name: 'Cabinet Painting', slug: 'cabinet-painting' },
      { name: 'Deck Staining', slug: 'deck-staining' },
      { name: 'Pressure Washing', slug: 'pressure-washing' },
      { name: 'Commercial Painting', slug: 'commercial-painting' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#2563eb', secondary: '#eff6ff' },
    aiName: 'Pat',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Denver', 'Aurora', 'Lakewood', 'Littleton', 'Centennial', 'Westminster', 'Thornton', 'Arvada', 'Boulder', 'Broomfield'],
  },
  flooring: {
    label: 'Flooring',
    services: [
      { name: 'Hardwood Flooring', slug: 'hardwood-flooring' },
      { name: 'Tile Installation', slug: 'tile-installation' },
      { name: 'Carpet Installation', slug: 'carpet-installation' },
      { name: 'Laminate Flooring', slug: 'laminate-flooring' },
      { name: 'Vinyl Flooring', slug: 'vinyl-flooring' },
      { name: 'Floor Refinishing', slug: 'floor-refinishing' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#92400e', secondary: '#fef3c7' },
    aiName: 'Frank',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Nashville', 'Franklin', 'Murfreesboro', 'Brentwood', 'Hendersonville', 'Gallatin', 'Lebanon', 'Mt Juliet', 'Spring Hill', 'Smyrna'],
  },
  remodeling: {
    label: 'Remodeling',
    services: [
      { name: 'Kitchen Remodeling', slug: 'kitchen-remodeling' },
      { name: 'Bathroom Remodeling', slug: 'bathroom-remodeling' },
      { name: 'Basement Finishing', slug: 'basement-finishing' },
      { name: 'Home Additions', slug: 'home-additions' },
      { name: 'Whole Home Remodel', slug: 'whole-home-remodel' },
      { name: 'Custom Cabinetry', slug: 'custom-cabinetry' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#d97706', secondary: '#1c1917' },
    aiName: 'Rob',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Portland', 'Beaverton', 'Tigard', 'Lake Oswego', 'Hillsboro', 'Gresham', 'Milwaukie', 'Oregon City', 'West Linn', 'Tualatin'],
  },
  'pest-control': {
    label: 'Pest Control',
    services: [
      { name: 'Termite Treatment', slug: 'termite-treatment' },
      { name: 'Rodent Control', slug: 'rodent-control' },
      { name: 'Bed Bug Treatment', slug: 'bed-bug-treatment' },
      { name: 'Ant Control', slug: 'ant-control' },
      { name: 'Mosquito Control', slug: 'mosquito-control' },
      { name: 'Wildlife Removal', slug: 'wildlife-removal' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#059669', secondary: '#111827' },
    aiName: 'Pete',
    needsGeoPages: true,
    defaultPageCount: 30,
    nearbyCities: ['Tampa', 'St Petersburg', 'Clearwater', 'Brandon', 'Riverview', 'Wesley Chapel', 'Palm Harbor', 'Largo', 'Dunedin', 'Safety Harbor'],
  },
  locksmith: {
    label: 'Locksmith',
    services: [
      { name: 'Emergency Lockout', slug: 'emergency-lockout' },
      { name: 'Lock Rekeying', slug: 'lock-rekeying' },
      { name: 'Lock Installation', slug: 'lock-installation' },
      { name: 'Car Lockout', slug: 'car-lockout' },
      { name: 'Key Duplication', slug: 'key-duplication' },
      { name: 'Safe Services', slug: 'safe-services' },
    ],
    designStyle: 'modern-dark',
    colors: { primary: '#f59e0b', secondary: '#18181b' },
    aiName: 'Leo',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['Las Vegas', 'Henderson', 'North Las Vegas', 'Paradise', 'Spring Valley', 'Summerlin', 'Enterprise', 'Boulder City', 'Mesquite', 'Pahrump'],
  },
  moving: {
    label: 'Moving',
    services: [
      { name: 'Local Moving', slug: 'local-moving' },
      { name: 'Long Distance Moving', slug: 'long-distance-moving' },
      { name: 'Packing Services', slug: 'packing-services' },
      { name: 'Commercial Moving', slug: 'commercial-moving' },
      { name: 'Storage Solutions', slug: 'storage-solutions' },
      { name: 'Piano Moving', slug: 'piano-moving' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#4f46e5', secondary: '#eef2ff' },
    aiName: 'Mike',
    needsGeoPages: true,
    defaultPageCount: 25,
    nearbyCities: ['San Diego', 'Chula Vista', 'Carlsbad', 'Oceanside', 'Escondido', 'El Cajon', 'La Mesa', 'Encinitas', 'Poway', 'San Marcos'],
  },
  salon: {
    label: 'Salon / Beauty',
    services: [
      { name: 'Haircuts & Styling', slug: 'haircuts-styling' },
      { name: 'Hair Coloring', slug: 'hair-coloring' },
      { name: 'Manicure & Pedicure', slug: 'manicure-pedicure' },
      { name: 'Waxing', slug: 'waxing' },
      { name: 'Facials', slug: 'facials' },
      { name: 'Bridal Services', slug: 'bridal-services' },
    ],
    designStyle: 'bold',
    colors: { primary: '#be185d', secondary: '#fdf2f8' },
    aiName: 'Stella',
    needsGeoPages: false,
    defaultPageCount: 12,
    nearbyCities: [],
  },
  medical: {
    label: 'Medical / Healthcare',
    services: [
      { name: 'Primary Care', slug: 'primary-care' },
      { name: 'Urgent Care', slug: 'urgent-care' },
      { name: 'Physical Therapy', slug: 'physical-therapy' },
      { name: 'Chiropractic', slug: 'chiropractic' },
      { name: 'Pediatrics', slug: 'pediatrics' },
      { name: 'Telehealth', slug: 'telehealth' },
    ],
    designStyle: 'clean-light',
    colors: { primary: '#0d9488', secondary: '#f0fdfa' },
    aiName: 'Dr. Kyra',
    needsGeoPages: false,
    defaultPageCount: 15,
    nearbyCities: [],
  },
  accounting: {
    label: 'Accounting',
    services: [
      { name: 'Tax Preparation', slug: 'tax-preparation' },
      { name: 'Bookkeeping', slug: 'bookkeeping' },
      { name: 'Payroll Services', slug: 'payroll-services' },
      { name: 'Business Tax Planning', slug: 'business-tax-planning' },
      { name: 'Audit Support', slug: 'audit-support' },
      { name: 'Financial Statements', slug: 'financial-statements' },
    ],
    designStyle: 'minimal',
    colors: { primary: '#1e3a5f', secondary: '#f8fafc' },
    aiName: 'Alex',
    needsGeoPages: false,
    defaultPageCount: 10,
    nearbyCities: [],
  },
};

export const DESIGN_STYLES = [
  { id: 'modern-dark', label: 'Modern Dark', description: 'Bold dark backgrounds with vibrant accents', preview: '🌙' },
  { id: 'clean-light', label: 'Clean Light', description: 'Crisp white layouts with subtle shadows', preview: '☀️' },
  { id: 'bold', label: 'Bold', description: 'Strong colors, large typography, high contrast', preview: '🔥' },
  { id: 'minimal', label: 'Minimal', description: 'Lots of whitespace, understated elegance', preview: '✨' },
] as const;

export const TONE_OPTIONS = [
  { id: 'professional', label: 'Professional', description: 'Polished and authoritative' },
  { id: 'friendly', label: 'Friendly', description: 'Warm and approachable' },
  { id: 'casual', label: 'Casual', description: 'Relaxed and conversational' },
] as const;

export const AI_CAPABILITIES = [
  { id: 'answer_questions', label: 'Answer questions' },
  { id: 'book_appointments', label: 'Book appointments' },
  { id: 'capture_leads', label: 'Capture leads' },
  { id: 'provide_quotes', label: 'Provide quotes' },
  { id: 'qualify_leads', label: 'Qualify leads' },
] as const;
