/**
 * Deal Autopilot
 *
 * AI actively works deals forward:
 * - Sends follow-ups for stale deals
 * - Handles common objections
 * - Schedules meetings
 * - Generates daily digest for agency owner
 *
 * Called from cron or manual trigger.
 */

import { createServiceClientWithoutCookies } from '@/lib/supabase/server';
import { logActivity } from './activities';
import { getMemories, buildMemoryContext } from './relationship-memory';
import { deductCredits, getAgencyCredits } from '@/lib/billing/credit-engine';

interface DealWithContext {
  id: string;
  name: string;
  value: number;
  stage: string;
  notes: string | null;
  contact_id: string | null;
  company_id: string | null;
  updated_at: string;
  contact?: { first_name: string | null; last_name: string | null; email: string | null; phone: string | null } | null;
  company?: { name: string } | null;
}

export interface AutopilotDigest {
  date: string;
  deals_worked: number;
  follow_ups_drafted: number;
  deals_progressed: number;
  actions: AutopilotAction[];
  summary: string;
}

interface AutopilotAction {
  deal_id: string;
  deal_name: string;
  contact_name: string;
  action_type: 'follow_up_drafted' | 'objection_handled' | 'meeting_suggested' | 'stage_recommendation' | 'alert';
  description: string;
  ai_draft?: string;
  priority: 'low' | 'medium' | 'high';
}

export async function runDealAutopilot(agencyId: string): Promise<AutopilotDigest> {
  const svc = createServiceClientWithoutCookies();
  const actions: AutopilotAction[] = [];

  const creditBalance = await getAgencyCredits(agencyId);
  if (creditBalance.balance < 5) {
    return {
      date: new Date().toISOString(),
      deals_worked: 0,
      follow_ups_drafted: 0,
      deals_progressed: 0,
      actions: [],
      summary: 'Insufficient credits for Deal Autopilot. Buy more credits to activate.',
    };
  }

  // Get active deals with contacts
  const { data: deals } = await svc
    .from('crm_deals')
    .select('*, crm_contacts!crm_deals_contact_id_fkey(first_name, last_name, email, phone), crm_companies!crm_deals_company_id_fkey(name)')
    .eq('agency_id', agencyId)
    .in('stage', ['prospect', 'qualified', 'proposal', 'negotiation'])
    .order('updated_at', { ascending: true });

  if (!deals?.length) {
    return {
      date: new Date().toISOString(),
      deals_worked: 0,
      follow_ups_drafted: 0,
      deals_progressed: 0,
      actions: [],
      summary: 'No active deals to work.',
    };
  }

  const now = Date.now();
  let creditsUsed = 0;
  const MAX_CREDITS = Math.min(10, creditBalance.balance);

  for (const rawDeal of deals) {
    if (creditsUsed >= MAX_CREDITS) break;

    const contact = (rawDeal as Record<string, unknown>).crm_contacts as Record<string, unknown> | null;
    const company = (rawDeal as Record<string, unknown>).crm_companies as Record<string, unknown> | null;
    const deal = rawDeal as unknown as DealWithContext;
    const daysSinceUpdate = Math.floor((now - new Date(deal.updated_at).getTime()) / 86400000);
    const contactName = contact ? `${contact.first_name || ''} ${contact.last_name || ''}`.trim() : 'Unknown';

    // Get relationship memory for context
    let memoryContext = '';
    if (deal.contact_id) {
      const memories = await getMemories(agencyId, deal.contact_id);
      memoryContext = buildMemoryContext(memories);
    }

    // Determine what action to take
    if (daysSinceUpdate >= 7) {
      // Stale deal — draft follow-up
      const draft = await generateAutopilotAction(deal, contactName, memoryContext, 'follow_up');
      if (draft) {
        actions.push({
          deal_id: deal.id,
          deal_name: deal.name,
          contact_name: contactName,
          action_type: 'follow_up_drafted',
          description: `Deal stale for ${daysSinceUpdate} days. Follow-up drafted.`,
          ai_draft: draft,
          priority: daysSinceUpdate > 14 ? 'high' : 'medium',
        });

        // Create task
        await svc.from('crm_tasks').insert({
          agency_id: agencyId,
          contact_id: deal.contact_id,
          deal_id: deal.id,
          title: `Follow up: ${deal.name}`,
          description: `Auto-generated by Deal Autopilot. ${daysSinceUpdate} days since last activity.`,
          type: 'follow_up',
          priority: daysSinceUpdate > 14 ? 'high' : 'medium',
          status: 'pending',
          due_date: new Date(now + 86400000).toISOString(),
          assigned_to: 'ai',
          created_by: 'ai',
          ai_draft: draft,
        });

        creditsUsed++;
      }
    } else if (daysSinceUpdate >= 3 && deal.stage === 'proposal') {
      // Proposal stage — check for objection handling
      const suggestion = await generateAutopilotAction(deal, contactName, memoryContext, 'stage_check');
      if (suggestion) {
        actions.push({
          deal_id: deal.id,
          deal_name: deal.name,
          contact_name: contactName,
          action_type: 'stage_recommendation',
          description: suggestion,
          priority: 'medium',
        });
        creditsUsed++;
      }
    }
  }

  // Deduct credits
  if (creditsUsed > 0) {
    await deductCredits(agencyId, 'crm_follow_up_draft', { multiplier: creditsUsed, description: `Deal Autopilot: ${creditsUsed} actions` });
  }

  // Generate summary
  const summary = `Deal Autopilot processed ${deals.length} active deals. ${actions.filter(a => a.action_type === 'follow_up_drafted').length} follow-ups drafted, ${actions.filter(a => a.action_type === 'stage_recommendation').length} stage recommendations.`;

  // Log digest to activity feed
  await logActivity(agencyId, {
    type: 'system',
    subject: 'Deal Autopilot Daily Digest',
    body: summary + '\n\n' + actions.map(a => `• ${a.deal_name}: ${a.description}`).join('\n'),
    actor: 'ai',
    actor_name: 'Deal Autopilot',
    needs_attention: actions.some(a => a.priority === 'high'),
    attention_type: actions.some(a => a.priority === 'high') ? 'review' : undefined,
  });

  return {
    date: new Date().toISOString(),
    deals_worked: deals.length,
    follow_ups_drafted: actions.filter(a => a.action_type === 'follow_up_drafted').length,
    deals_progressed: actions.filter(a => a.action_type === 'stage_recommendation').length,
    actions,
    summary,
  };
}

async function generateAutopilotAction(
  deal: DealWithContext,
  contactName: string,
  memoryContext: string,
  actionType: 'follow_up' | 'stage_check',
): Promise<string | null> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return null;

  const prompt = actionType === 'follow_up'
    ? `Draft a warm, personalized follow-up message (under 60 words) for:
Deal: ${deal.name} ($${Number(deal.value).toLocaleString()}, stage: ${deal.stage})
Contact: ${contactName}
Notes: ${deal.notes || 'None'}
${memoryContext ? `\nRelationship Memory:\n${memoryContext}` : ''}

Use personal details naturally if available. Don't be generic.`
    : `Analyze this deal and suggest the best next step (1-2 sentences):
Deal: ${deal.name} ($${Number(deal.value).toLocaleString()}, stage: ${deal.stage})
Contact: ${contactName}
Notes: ${deal.notes || 'None'}
${memoryContext ? `\nRelationship Memory:\n${memoryContext}` : ''}`;

  try {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: 'You are a sales AI assistant. Be concise, warm, and specific.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.7,
        max_tokens: 200,
      }),
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data.choices?.[0]?.message?.content || null;
  } catch {
    return null;
  }
}
