import Link from 'next/link';
import type { Metadata } from 'next';
import PublicNav from '@/components/layout/public-nav';
import PublicFooter from '@/components/layout/public-footer';

export const metadata: Metadata = {
  title: 'Terms of Service — Kyra AI',
  description: 'Terms governing use of the Kyra AI Employee Platform.',
};

const LAST_UPDATED = 'February 22, 2026';
const COMPANY = 'Conversion System';
const EMAIL = 'angel@conversionsystem.com';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <PublicNav />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-3xl font-black mb-2">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-10">Last updated: {LAST_UPDATED}</p>

        <p className="text-slate-300 leading-relaxed mb-8">
          By accessing or using Kyra (kyra.conversionsystem.com), operated by {COMPANY}, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform.
        </p>

        {[
          {
            title: '1. Service Description',
            items: [
              'Kyra is an AI employee platform that deploys automated AI agents inside GoHighLevel agency accounts and other channels.',
              'The platform enables agencies to configure and manage AI employees for their business clients.',
              'AI-generated responses are automated. {COMPANY} does not review individual AI responses in real time.',
            ],
          },
          {
            title: '2. Eligibility',
            items: [
              'You must be at least 18 years old to use Kyra.',
              'You must have legal authority to represent the agency and clients you manage through the platform.',
              'You must comply with GoHighLevel\'s terms of service when using the GHL integration.',
            ],
          },
          {
            title: '3. Account Responsibilities',
            items: [
              'You are responsible for maintaining the security of your account credentials.',
              'You are responsible for all activity that occurs under your account.',
              'You must promptly notify us at ' + EMAIL + ' of any unauthorized use.',
              'You are responsible for configuring AI personalities appropriately for your clients\' businesses.',
            ],
          },
          {
            title: '4. Acceptable Use',
            items: [
              'You may not use Kyra to send spam, unsolicited messages, or violate TCPA or CAN-SPAM regulations.',
              'You must comply with all applicable SMS and messaging laws, including honoring opt-out requests.',
              'You may not use the platform to harass, deceive, or defraud end users.',
              'You may not attempt to reverse-engineer, resell infrastructure, or circumvent usage limits.',
              'AI employees must be disclosed as AI to end users upon request.',
            ],
          },
          {
            title: '5. Billing and Payment',
            items: [
              'Paid plans are billed monthly via Stripe.',
              'All plans include a 30-day free trial; no credit card required to start.',
              'Cancellation takes effect at the end of the current billing period; no prorated refunds.',
              'We reserve the right to suspend accounts with overdue payments.',
            ],
          },
          {
            title: '6. AI Limitations and Disclaimer',
            items: [
              'AI responses are generated by large language models and may contain errors, inaccuracies, or inappropriate content.',
              'You are responsible for reviewing AI personality configurations and monitoring AI behavior.',
              '{COMPANY} is not liable for actions taken by end users based on AI responses.',
              'AI employees should not be used as the sole method of communication for medical, legal, or financial advice.',
            ],
          },
          {
            title: '7. Data and Privacy',
            items: [
              'Your use of Kyra is also governed by our Privacy Policy.',
              'By using the platform, you represent that you have obtained necessary consent from your clients\' end users to process their messages through AI systems.',
              'You retain ownership of your client data; we process it only to provide the service.',
            ],
          },
          {
            title: '8. Intellectual Property',
            items: [
              'Kyra, its design, and underlying technology are owned by {COMPANY}.',
              'You retain ownership of AI personalities and content you create on the platform.',
              'You grant {COMPANY} a limited license to use your content to provide the service.',
            ],
          },
          {
            title: '9. Termination',
            items: [
              'We may suspend or terminate your account for violations of these terms, with or without notice.',
              'You may cancel your account at any time via account settings or by emailing ' + EMAIL + '.',
              'Upon termination, your data will be retained for 30 days then deleted.',
            ],
          },
          {
            title: '10. Limitation of Liability',
            items: [
              'To the maximum extent permitted by law, {COMPANY} shall not be liable for indirect, incidental, special, or consequential damages.',
              'Our total liability to you shall not exceed the amount you paid us in the 3 months preceding the claim.',
              'We provide the service "as is" without warranty of any kind.',
            ],
          },
          {
            title: '11. Governing Law',
            items: [
              'These terms are governed by the laws of the State of California, United States.',
              'Disputes shall be resolved by binding arbitration in California, except where prohibited by law.',
            ],
          },
          {
            title: '12. Changes to Terms',
            items: [
              'We may update these terms periodically. Continued use after changes constitutes acceptance.',
              'Material changes will be communicated via email to account holders.',
            ],
          },
          {
            title: '13. Contact',
            items: [
              'Questions about these terms? Email ' + EMAIL + '.',
            ],
          },
        ].map(section => (
          <div key={section.title} className="mb-8">
            <h2 className="text-lg font-bold text-white mb-3">{section.title}</h2>
            <ul className="space-y-2">
              {section.items.map((item, i) => (
                <li key={i} className="text-slate-300 text-sm leading-relaxed flex gap-2">
                  <span className="text-indigo-400 shrink-0 mt-0.5">•</span>
                  <span>{item.replace(/\{COMPANY\}/g, COMPANY)}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}

        <div className="border-t border-white/10 pt-8 mt-8">
          <p className="text-slate-500 text-sm">
            {COMPANY} · {EMAIL} · <Link href="/privacy" className="text-indigo-400 hover:underline">Privacy Policy</Link>
          </p>
        </div>
      </div>
      <PublicFooter />
    </div>
  );
}
