/**
 * Integrations Sync — syncs integration status to a client's OpenClaw container.
 *
 * After connecting/disconnecting GHL (or any future integration),
 * call syncIntegrationsToContainer(clientId) to write INTEGRATIONS.md
 * to the container workspace so the AI knows what tools are available.
 *
 * NEVER includes access tokens, API keys, or secrets — only lists
 * what's connected and what actions the AI can perform.
 */

import { createServiceClientWithoutCookies } from '@/lib/supabase/server';
import { writeWorkspaceFile, wakeContainerAI } from '@/lib/ovh/sync';

// ── GHL tool definitions (from template system) ────────────────────────────

const GHL_TOOLS = [
  { name: 'book_appointment', description: 'Schedule appointments in GHL calendar' },
  { name: 'tag_contact', description: 'Add/remove tags on contacts' },
  { name: 'create_opportunity', description: 'Create sales pipeline opportunities' },
  { name: 'escalate_to_human', description: 'Transfer conversation to human agent' },
  { name: 'send_sms', description: 'Send SMS messages to contacts' },
  { name: 'send_email', description: 'Send email to contacts' },
  { name: 'search_contacts', description: 'Search and look up contacts in the CRM' },
  { name: 'update_contact', description: 'Update contact fields and custom values' },
];

// ── Main sync function ─────────────────────────────────────────────────────

/**
 * Read integration state for a client from Supabase, build INTEGRATIONS.md,
 * and write it to the container workspace.
 *
 * Call this after:
 * - GHL OAuth connect (callback)
 * - GHL private token connect
 * - GHL disconnect
 * - Any future integration connect/disconnect
 */
export async function syncIntegrationsToContainer(clientId: string): Promise<void> {
  try {
    const supabase = createServiceClientWithoutCookies();

    // Read client record (integration fields + gateway info)
    const { data: client, error } = await supabase
      .from('agency_clients')
      .select(
        'id, name, ghl_location_id, ghl_access_token, ghl_private_token, ghl_connected_at, gateway_url, gateway_token, settings'
      )
      .eq('id', clientId)
      .single();

    if (error || !client) {
      console.error(`[integrations-sync] Client ${clientId} not found:`, error?.message);
      return;
    }

    // Build INTEGRATIONS.md content
    const content = buildIntegrationsMd(client);

    // Write to container
    const writeResult = await writeWorkspaceFile(clientId, 'INTEGRATIONS.md', content);
    if (!writeResult.ok) {
      console.error(
        `[integrations-sync] Failed to write INTEGRATIONS.md for client ${clientId}:`,
        writeResult.error
      );
      return;
    }

    // Wake the AI so it re-reads workspace files
    const gatewayUrl = client.gateway_url as string | null;
    const gatewayToken = client.gateway_token as string | null;
    if (gatewayUrl && gatewayToken) {
      await wakeContainerAI(
        gatewayUrl,
        gatewayToken,
        '[System] Integrations updated. Re-read INTEGRATIONS.md for available tools and connections.'
      );
    }

    console.log(`[integrations-sync] Synced INTEGRATIONS.md for client ${clientId}`);
  } catch (err) {
    console.error(
      `[integrations-sync] Unexpected error for client ${clientId}:`,
      err instanceof Error ? err.message : err
    );
  }
}

// ── Markdown builder ───────────────────────────────────────────────────────

interface ClientRow {
  id: string;
  name: string;
  ghl_location_id: string | null;
  ghl_access_token: string | null;
  ghl_private_token: string | null;
  ghl_connected_at: string | null;
  settings: Record<string, unknown> | null;
}

function buildIntegrationsMd(client: ClientRow): string {
  const sections: string[] = [];

  sections.push('# Integrations');
  sections.push('');
  sections.push('This file lists all connected integrations and the tools they provide.');
  sections.push('It is auto-generated by the dashboard — do not edit manually.');
  sections.push('');

  // ── GHL Section ──────────────────────────────────────────────────────
  const ghlConnected = !!(
    client.ghl_location_id &&
    (client.ghl_access_token || client.ghl_private_token)
  );

  sections.push('## GoHighLevel (GHL)');
  sections.push('');

  if (ghlConnected) {
    sections.push(`- **Status:** ✅ Connected`);
    sections.push(`- **Location ID:** \`${client.ghl_location_id}\``);
    if (client.ghl_connected_at) {
      sections.push(`- **Connected at:** ${client.ghl_connected_at}`);
    }
    sections.push('');
    sections.push('### Available Actions');
    sections.push('');
    sections.push('You can use these tools to interact with the CRM:');
    sections.push('');
    for (const tool of GHL_TOOLS) {
      sections.push(`- **\`${tool.name}\`** — ${tool.description}`);
    }
    sections.push('');
    sections.push('### Usage Notes');
    sections.push('');
    sections.push('- All GHL API calls are authenticated automatically — you do not need tokens.');
    sections.push('- Use the Location ID above when GHL tools require it.');
    sections.push('- When a customer messages, their GHL contact is auto-matched by phone/email.');
    sections.push('- To escalate a conversation, use `escalate_to_human` — this transfers to a human agent in GHL.');
  } else {
    sections.push(`- **Status:** ❌ Not connected`);
    sections.push('');
    sections.push('GHL is not connected. CRM tools (booking, tagging, opportunities) are unavailable.');
    sections.push('Ask the business owner to connect GHL from the dashboard.');
  }

  // ── Google Calendar (check settings for google integration) ──────────
  const settings = client.settings || {};
  const googleConnected = !!(settings as Record<string, unknown>).google_calendar_connected;

  if (googleConnected) {
    sections.push('');
    sections.push('## Google Calendar');
    sections.push('');
    sections.push('- **Status:** ✅ Connected');
    sections.push('- You can check availability and create calendar events.');
  }

  // ── Footer ───────────────────────────────────────────────────────────
  sections.push('');
  sections.push('---');
  sections.push(`*Last synced: ${new Date().toISOString()}*`);

  return sections.join('\n');
}
