-- AI-Generated HTML Templates
-- Adds support for AI-custom HTML generation mode alongside existing template-based approach.

-- Store generated HTML per page
ALTER TABLE site_pages
ADD COLUMN IF NOT EXISTS html_content TEXT;

-- Track whether the site uses template-based or AI-custom generation
ALTER TABLE client_sites
ADD COLUMN IF NOT EXISTS generation_mode TEXT DEFAULT 'template';

-- Store the gallery template selection (e.g., 'generic', 'ai-custom')
ALTER TABLE client_sites
ADD COLUMN IF NOT EXISTS template_preset TEXT;

-- Add comment for documentation
COMMENT ON COLUMN site_pages.html_content IS 'Full HTML document generated by AI HTML engine (only used when generation_mode = ai-custom)';
COMMENT ON COLUMN client_sites.generation_mode IS 'Content generation mode: template (default) or ai-custom (AI generates full HTML)';
COMMENT ON COLUMN client_sites.template_preset IS 'Selected template preset from the gallery (e.g., generic, ai-custom)';
