'use client';

import Link from 'next/link';
import { useState, useEffect } from 'react';
import { Check, BadgePercent } from 'lucide-react';
import { pixel } from '@/components/analytics/MetaPixel';
import PublicNav from '@/components/layout/public-nav';
import PublicFooter from '@/components/layout/public-footer';

const PLANS = [
  {
    name: 'Lite',
    monthly: 99, annual: 79,
    annualSave: 240,
    period: '/month',
    desc: 'Launch your AI agency with 3 clients — each gets a full website + AI worker + CRM.',
    cta: 'Get Started — Build Your First Site',
    href: '/website-builder?plan=starter',
    featured: false,
    badge: 'Start here',
    revenueCallout: 'Charge $500–800/mo per client = $1,500–2,400/mo revenue on $99 cost',
    features: [
      '3 client AI workers',
      'AI Website Builder — 15-25 SEO-optimized pages per client',
      'Lead capture forms + CRM sync',
      '5,000 platform credits / month',
      '🌍 500 web scrapes/mo — AI workers can read the internet',
      '21 industry templates',
      'Telegram, SMS, web chat',
      'CRM integration',
      'AI Sales Pipeline',
      'Smart escalation alerts',
      'Weekly performance reports',
    ],
    limits: [],
  },
  {
    name: 'Pro',
    monthly: 299, annual: 239,
    annualSave: 720,
    period: '/month',
    desc: 'Full AI workforce — up to 10 clients, each with website + AI worker + CRM.',
    cta: 'Get Started — Build Your First Site',
    href: '/website-builder?plan=pro',
    featured: true,
    badge: 'Best for growing agencies',
    revenueCallout: 'Charge $800–1,200/mo per client = $8,000–12,000/mo revenue on $299 cost',
    features: [
      '10 client AI workers',
      'AI Website Builder — 15-25 SEO-optimized pages per client',
      'Lead capture forms + CRM sync',
      'Growth Engine — AI-powered SEO page generation',
      '15,000 platform credits / month',
      '🌍 2,000 web scrapes/mo — full web intelligence',
      'Everything in Lite',
      'White-label branding',
      'Custom AI personalities',
      'Review queue (human-in-the-loop)',
      'Revenue tracking dashboard',
      'Priority support',
    ],
    limits: [],
  },
  {
    name: 'Scale',
    monthly: 499, annual: 399,
    annualSave: 1200,
    period: '/month',
    desc: 'Built for high-volume agencies — 20 clients, each with the full Business in a Box.',
    cta: 'Get Started — Build Your First Site',
    href: '/website-builder?plan=scale',
    featured: false,
    badge: 'For high-volume agencies',
    revenueCallout: 'Charge $1,000–2,000/mo per client = $20,000–40,000/mo revenue on $499 cost',
    features: [
      '20 client AI workers',
      'AI Website Builder — 15-25 SEO-optimized pages per client',
      'Lead capture forms + CRM sync',
      'Growth Engine — AI-powered SEO page generation',
      '30,000 platform credits / month',
      '🌍 5,000 web scrapes/mo — full automation stack',
      'Everything in Pro',
      'AI Sales Pipeline (unlimited + priority)',
      'Dedicated infrastructure',
      'Outbound webhooks',
      'Alert monitoring',
      'Dedicated Slack support',
      'API access',
    ],
    limits: [],
  },
];

const FAQ = [
  {
    q: 'What does each client actually get?',
    a: 'Every client gets a 15-25 page SEO-optimized website (generated by AI in minutes), an AI worker (chat widget that books appointments, captures leads, answers questions 24/7), a CRM that collects every lead, and access to the Growth Engine for ongoing SEO page generation.',
  },
  {
    q: 'Do I need GoHighLevel to use Kyra?',
    a: 'No. GHL is optional — it unlocks SMS, email, and multi-channel features. The website builder, AI worker chat widget, and CRM work on their own without GHL.',
  },
  {
    q: 'How do agencies make money with Kyra?',
    a: 'You pay $99–$499/mo for Kyra. You charge each client $500–$2,000/mo for their website + AI worker + CRM. At Pro ($299/mo, 10 clients) billing $1,000/client = $10,000/mo revenue — $9,751/mo margin. The math works from day one.',
  },
  {
    q: 'How long does it take to set up a new client?',
    a: 'Under 10 minutes. Enter the business info, Kyra generates a 15-25 page SEO-optimized website, deploys an AI worker trained on the business, and sets up the CRM. You can customize everything after.',
  },
  {
    q: 'Is there a long-term contract?',
    a: 'Monthly plans cancel anytime. Annual plans are billed upfront for the year and save 20%. 1 free account on all plans.',
  },
  {
    q: 'What happens if my client count exceeds my plan?',
    a: 'You\'ll see a prompt to upgrade before adding more clients. Existing clients are never interrupted.',
  },
];

export default function PricingPage() {
  const [annual, setAnnual] = useState(false);

  useEffect(() => {
    pixel.viewContent('Pricing Page');
  }, []);

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <PublicNav />

      {/* Header */}
      <section className="py-20 text-center px-4">
        <div className="inline-flex items-center gap-2 bg-white/10 rounded-full px-4 py-1.5 text-sm font-medium mb-6">
          Agency from $99/mo · 1 free account included — no credit card needed
        </div>
        <h1 className="text-4xl sm:text-5xl font-black mb-4">
          Your cost: $99–499/mo. Your client pays: $500–2,000/mo.
        </h1>
        <p className="text-slate-400 text-lg max-w-xl mx-auto mb-6">
          Every plan includes a 15-25 page SEO-optimized website, AI worker, CRM, and lead capture per client. The math works from day one.
        </p>
      </section>

      {/* Billing toggle */}
      <section className="max-w-6xl mx-auto px-4 pb-4 text-center">
        <div className="inline-flex items-center gap-3 bg-white/10 rounded-full p-1.5 border border-white/10">
          <button
            onClick={() => setAnnual(false)}
            className={`px-5 py-2 rounded-full text-sm font-semibold transition-all ${!annual ? 'bg-white text-gray-900 shadow' : 'text-slate-400 hover:text-white'}`}
          >
            Monthly
          </button>
          <button
            onClick={() => setAnnual(true)}
            className={`flex items-center gap-2 px-5 py-2 rounded-full text-sm font-semibold transition-all ${annual ? 'bg-white text-gray-900 shadow' : 'text-slate-400 hover:text-white'}`}
          >
            Annual
            <span className={`text-xs font-bold px-2 py-0.5 rounded-full transition-colors ${annual ? 'bg-green-500 text-white' : 'bg-green-800/60 text-green-300'}`}>
              Save 20%
            </span>
          </button>
        </div>
      </section>

      {/* Plans */}
      <section className="max-w-6xl mx-auto px-4 pb-20">
        <div className="grid sm:grid-cols-3 gap-4">
          {PLANS.map((plan) => {
            const price = annual && plan.annual > 0 ? plan.annual : plan.monthly;
            const displayPrice = price === 0 ? '$0' : `$${price}`;
            const hrefWithBilling = annual && plan.annual > 0
              ? plan.href + (plan.href.includes('?') ? '&billing=annual' : '?billing=annual')
              : plan.href;

            return (
              <div
                key={plan.name}
                className={`relative rounded-2xl border flex flex-col ${
                  plan.featured
                    ? 'border-indigo-500 bg-indigo-950/50'
                    : 'border-white/10 bg-white/5'
                }`}
              >
                {plan.badge && (
                  <div className={`text-xs font-semibold px-3 py-1.5 rounded-t-2xl text-center ${
                    plan.featured ? 'bg-indigo-600 text-white' : 'bg-white/10 text-slate-300'
                  }`}>
                    {plan.badge}
                  </div>
                )}
                <div className="p-6 flex flex-col flex-1">
                  <div className="mb-4">
                    <h2 className="text-lg font-bold">{plan.name}</h2>
                    <div className="flex items-baseline gap-1 mt-1">
                      <span className="text-3xl font-black">{displayPrice}</span>
                      <span className="text-slate-400 text-sm">/month</span>
                    </div>
                    {annual && plan.annualSave && (
                      <div className="flex items-center gap-1.5 mt-1.5">
                        <BadgePercent className="h-3.5 w-3.5 text-green-400" />
                        <span className="text-xs text-green-400 font-semibold">
                          Save ${plan.annualSave}/year
                        </span>
                      </div>
                    )}
                    {!annual && plan.annualSave && (
                      <p className="text-xs text-slate-600 mt-1.5">
                        Switch to annual &rarr; save ${plan.annualSave}/year
                      </p>
                    )}
                    <p className="text-slate-400 text-sm mt-2">{plan.desc}</p>
                  </div>

                  {/* Revenue callout */}
                  {plan.revenueCallout && (
                    <div className="bg-green-950/50 border border-green-800/40 rounded-xl px-4 py-3 mb-4">
                      <p className="text-xs text-green-400 font-semibold leading-relaxed">{plan.revenueCallout}</p>
                    </div>
                  )}

                  <ul className="space-y-2 mb-6 flex-1">
                    {plan.features.map((f) => (
                      <li key={f} className="flex items-start gap-2 text-sm">
                        <Check className="h-4 w-4 text-green-400 shrink-0 mt-0.5" />
                        <span>{f}</span>
                      </li>
                    ))}
                    {plan.limits.map((l) => (
                      <li key={l} className="flex items-start gap-2 text-sm text-slate-500">
                        <span className="text-slate-600 shrink-0 mt-0.5">&mdash;</span>
                        <span>{l}</span>
                      </li>
                    ))}
                  </ul>

                  <Link
                    href={hrefWithBilling}
                    className={`block text-center py-3 px-4 rounded-xl font-bold text-sm transition ${
                      plan.featured
                        ? 'bg-indigo-600 hover:bg-indigo-500 text-white'
                        : 'bg-white/10 hover:bg-white/15 border border-white/10 text-white'
                    }`}
                  >
                    {plan.cta}
                  </Link>
                </div>
              </div>
            );
          })}
        </div>

        {/* Voice Add-on */}
        <div className="mt-6 rounded-2xl border border-emerald-500/30 bg-emerald-950/30 p-5 sm:p-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="font-bold text-emerald-400 text-sm uppercase tracking-wide">Voice AI Add-on</span>
                <span className="text-xs bg-emerald-800/50 text-emerald-300 px-2 py-0.5 rounded-full">Works on any plan</span>
              </div>
              <p className="text-2xl font-black text-white">$79<span className="text-slate-400 text-base font-normal">/mo</span>
                <span className="text-sm text-slate-400 font-normal ml-2">or $63/mo billed annually</span>
              </p>
              <p className="text-slate-400 text-sm mt-1">300 AI calling minutes · inbound + outbound · transcripts · auto-escalation to human</p>
            </div>
            <a
              href="/website-builder?addon=voice"
              className="shrink-0 bg-emerald-600 hover:bg-emerald-500 text-white font-bold px-6 py-3 rounded-xl transition text-sm whitespace-nowrap"
            >
              Add Voice AI
            </a>
          </div>
        </div>

        {/* Credits callout */}
        <div className="mt-6 rounded-2xl border border-indigo-500/30 bg-indigo-950/40 p-5 text-center">
          <p className="text-indigo-200 text-sm font-semibold">
            Platform credits are included — no API keys needed to start. BYOK available on Lite+.
          </p>
        </div>

        {/* Annual savings bar */}
        {annual && (
          <div className="mt-6 rounded-2xl border border-green-800/40 bg-green-950/30 p-5 flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <BadgePercent className="h-6 w-6 text-green-400" />
              <div>
                <p className="font-bold text-white">Annual billing saves you real money</p>
                <p className="text-sm text-green-300/70">Pro plan: save $600/yr · Scale: save $1,200/yr</p>
              </div>
            </div>
            <span className="text-xs text-green-400 border border-green-700 rounded-full px-3 py-1">
              Billed as one annual payment
            </span>
          </div>
        )}

        {/* ROI callout */}
        <div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-6 sm:p-8 text-center">
          <p className="text-slate-400 text-sm mb-1">At Pro plan {annual ? '($239/mo annual)' : '($299/mo)'} with just 5 clients billed at $1,000/mo each:</p>
          <p className="text-2xl font-black text-green-400">
            $5,000/mo revenue · ${annual ? '4,761' : '4,701'}/mo margin
          </p>
          <p className="text-slate-500 text-xs mt-1">Each client gets: 15-25 page SEO-optimized website + AI worker + CRM + lead capture</p>
        </div>
      </section>

      {/* Feature comparison */}
      <section className="max-w-4xl mx-auto px-4 pb-20">
        <h2 className="text-2xl font-black text-center mb-3">What&apos;s included at each tier</h2>
        <p className="text-slate-400 text-sm text-center mb-10">Higher tiers unlock more built-in intelligence features.</p>
        <div className="rounded-2xl border border-white/10 overflow-hidden">
          <div className="grid grid-cols-4 bg-white/5 border-b border-white/10 px-4 py-3">
            <span className="text-sm font-semibold text-slate-300">Feature</span>
            <span className="text-sm font-semibold text-slate-300 text-center">Lite</span>
            <span className="text-sm font-semibold text-indigo-400 text-center">Pro</span>
            <span className="text-sm font-semibold text-slate-300 text-center">Scale</span>
          </div>
          {[
            { feature: 'AI chat + CRM', lite: true, pro: true, scale: true },
            { feature: '50 credits welcome gift', lite: true, pro: true, scale: true },
            { feature: 'AI Website Builder', lite: true, pro: true, scale: true },
            { feature: 'Lead scoring', lite: false, pro: true, scale: true },
            { feature: 'A/B testing', lite: false, pro: true, scale: true },
            { feature: 'Deal autopilot', lite: false, pro: true, scale: true },
            { feature: 'Multi-agent routing', lite: false, pro: true, scale: true },
            { feature: 'Competitive intelligence', lite: false, pro: true, scale: true },
            { feature: 'Review management', lite: false, pro: true, scale: true },
            { feature: 'Payment collection', lite: false, pro: true, scale: true },
            { feature: 'Dedicated infrastructure', lite: false, pro: false, scale: true },
            { feature: 'API access', lite: false, pro: false, scale: true },
            { feature: 'Priority support', lite: false, pro: true, scale: true },
            { feature: 'Custom integrations', lite: false, pro: false, scale: true },
          ].map((row, i) => (
            <div key={i} className={`grid grid-cols-4 px-4 py-3 border-b border-white/5 last:border-0 ${!row.lite && row.pro ? 'bg-indigo-950/20' : ''}`}>
              <span className="text-sm text-slate-300">{row.feature}</span>
              <span className="text-center">{row.lite ? <Check className="h-4 w-4 text-green-400 inline" /> : <span className="text-slate-600">—</span>}</span>
              <span className="text-center">{row.pro ? <Check className="h-4 w-4 text-indigo-400 inline" /> : <span className="text-slate-600">—</span>}</span>
              <span className="text-center">{row.scale ? <Check className="h-4 w-4 text-green-400 inline" /> : <span className="text-slate-600">—</span>}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Belief Shifts */}
      <section className="max-w-3xl mx-auto px-4 pb-20">
        <h2 className="text-2xl font-black text-center mb-3">Still on the fence?</h2>
        <p className="text-slate-400 text-sm text-center mb-10">Every objection you have — we&apos;ve heard it. Here&apos;s the truth.</p>
        <div className="space-y-4">
          {[
            {
              old: '"I need to be technical to set up websites and AI."',
              truth: 'Enter the business name, industry, and location. Kyra generates a 15-25 page SEO-optimized website, deploys an AI worker, and sets up the CRM. Under 10 minutes. Zero code.',
            },
            {
              old: '"My clients already have websites."',
              truth: 'Most small business websites are 5 pages with zero SEO value. Kyra generates 15-25 pages targeting local search terms — service pages, city pages, blog posts, FAQ. It\'s not just a website, it\'s a lead generation machine.',
            },
            {
              old: '"I don\'t have time to manage client sites."',
              truth: 'The Growth Engine suggests new pages to grow your search presence. One click to generate and publish. Sites keep growing with AI-generated content. you manage 20 clients from one dashboard.',
            },
            {
              old: '"AI chatbots don\'t actually work."',
              truth: 'This isn\'t a chatbot. It\'s an AI worker trained on the specific business — services, pricing, hours, policies. It books appointments, captures leads, and answers questions. 24/7. On the website you built for them.',
            },
            {
              old: '"I can\'t justify the cost to clients."',
              truth: 'A custom website alone costs $3,000–10,000 upfront. A virtual receptionist costs $500+/mo. Kyra gives them both plus a CRM for $500–2,000/mo. The value is obvious.',
            },
          ].map((item, i) => (
            <div key={i} className="border border-white/10 rounded-xl p-5 bg-white/[0.02]">
              <p className="text-red-400 text-sm font-semibold line-through opacity-70 mb-2">{item.old}</p>
              <p className="text-slate-300 text-sm leading-relaxed">{item.truth}</p>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-4 pb-24">
        <h2 className="text-2xl font-black text-center mb-10">Frequently asked questions</h2>
        <div className="space-y-6">
          {FAQ.map((item) => (
            <div key={item.q} className="border-b border-white/10 pb-6">
              <h3 className="font-bold text-white mb-2">{item.q}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{item.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-white/10 py-20 text-center px-4">
        <h2 className="text-3xl sm:text-4xl font-black mb-4">First client site live in 10 minutes.</h2>
        <p className="text-slate-400 mb-8">Start on Lite at $99/mo. 1 free account included — no credit card needed.</p>
        <Link
          href="/website-builder"
          className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-lg px-8 py-4 rounded-xl transition"
        >
          Try It Free — Build Your First Site →
        </Link>
        <p className="text-slate-600 text-sm mt-4">Cancel anytime · Upgrade as you grow · Website + AI worker + CRM included</p>
      </section>

      <PublicFooter />
    </div>
  );
}
